### PR TITLE
Fix uninitialized user claim

### LINKED ISSUE #1874: Some providers has uninitialized user claim
Keycloak OIDC (among others) doesn't call `setProviderDefaults` therefore UserClaim is never initialized with the default value (sub) and stay an empty string. This leads to an empty user.

Should be closed by PR #1873 

## Expected Behavior

`user` value present in the session.

## Current Behavior

When using Keycloak OIDC, `user` value is empty

## Your Environment

- Version used: 7.4.0

### PR DESCRIPTION
**Pull request by babs**
## Description

Some providers doesn't initialize data with `setProviderDefaults` function (keycloak-oidc for example), therefore `UserClaim` is never initialized with the default value (`sub`) and stay an empty string. This leads to an empty user.

Should close #1874

## Checklist:

- [X] My change requires a change to the documentation or CHANGELOG.
- [X] I have updated the documentation/CHANGELOG accordingly.
- [X] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

File: providers/provider_data.go [hunk 1]
```diff
@@ -197,10 +197,6 @@ func (p *ProviderData) setProviderDefaults(defaults providerDefaults) {
 	if p.Scope == "" {
 		p.Scope = defaults.scope
 	}
-
```
Comment (JoelSpeed) [inline providers/provider_data.go:200]: Why not make sure every provider is using `setProviderDefaults`? Does every provider definitely use `buildSessionFromClaims`?

Moving it to `buildSessionFromClaims` means the check is done on every authentication request rather than just in set up, so there's an efficiency hit too

**Comment by babs** [comment]
Updated with `setProviderDefaults` approach:
```
	p.setProviderDefaults(providerDefaults{
		name:        keycloakOIDCProviderName,
	})
```

**Comment by babs** [comment]
Just for the sake of testing live, could you test the v7.4.0-babs3 release on my fork before going back to 7.2.0 ?
For security concerns, the build has been performed by github action, so every thing is traceable.

**Review by JoelSpeed — DISMISSED** [review]
LGTM, thanks @babs

**Review by JoelSpeed — APPROVED** [review]
