### PR TITLE
fix: handle Unix socket RemoteAddr in IP resolution

### LINKED ISSUE #3373: [Bug]: oauth2-proxy tries to obtain source ip when listening on socket
### OAuth2-Proxy Version

v7.14.3

### Provider

None

### Expected Behaviour

When listening on a socket, there is no source ip, so oauth2-proxy should no try to obtain it.

### Current Behaviour

For every request, I get `[oauthproxy.go:622] Error obtaining real IP for trusted IP list: unable to get ip and port from http.RemoteAddr (@)` in the log. 

### Steps To Reproduce

TL;DR:
1. Run oauth2-proxy like like documented [here](https://oauth2-proxy.github.io/oauth2-proxy/7.8.x/configuration/systemd_socket/)
2. Make requests
3. Check the logs 

Long version:
1. Run oauth2-proxy with env `OAUTH2_PROXY_HTTP_ADDRESS=fd:3` (should work the same with file path)
2. Make sure `OAUTH2_PROXY_REVERSE_PROXY` is not set or set to false
3. Make requests to the socket (probably using a reverse proxy like caddy or nginx)
4. Check logs
5. See errors
6. Full configurations in configuration details

### Possible Solutions

- Silence the error when trusted ips is not set
- When trusted ips is set with socket listener, give error like "Trusted ips setting doesn't work with socket listener, unless --reverse-proxy=true is set"

### Configuration details or additional information

Systemd socket:

`/etc/systemd/system/oauth2-proxy.socket`
```
[Unit]
Description=oauth2-proxy socket

[Socket]
ListenStream=/run/oauth2-proxy.sock
```

I'm running in podman with the following quadlet file:

`/etc/containers/systemd/oauth2-proxy.container`:
```
[Container]
ContainerName=oauth2-proxy
Environment=OAUTH2_PROXY_HTTP_ADDRESS=fd:3
Environment=OAUTH2_PROXY_PROVIDER=oidc
Environment=OAUTH2_PROXY_OIDC_ISSUER_URL=https://---
Environment=OAUTH2_PROXY_CLIENT_ID=---
Environment=OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
Environment=OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
Environment='OAUTH2_PROXY_EMAIL_DOMAINS=*'
Exec=--client-secret-file /run/secrets/client-secret --cookie-secret-file /run/secrets/cookie-secret
Image=quay.io_oauth2-proxy_oauth2-proxy:latest-alpine.image
Network=oauth2-proxy.network
Secret=oauth2-proxy-cookie-secret,type=mount,target=cookie-secret
Secret=oauth2-proxy-client-secret,type=mount,target=client-secret
AutoUpdate=registry

[Unit]
Description=Container oauth2-proxy
StartLimitIntervalSec=30
StartLimitBurst=3
[Service]
OOMPolicy=stop

[Service]
Restart=always

[Install]
WantedBy=multi-user.target
```

### PR DESCRIPTION
**Pull request by H1net**
## Summary

Fixes #3373

When `oauth2-proxy` listens on a Unix domain socket (e.g. `--http-address=fd:3` or a socket file path), Go's `net` package sets `http.Request.RemoteAddr` to `"@"` rather than the usual `"host:port"` format. This caused `net.SplitHostPort` to fail on every incoming request, flooding logs with:

```
Error obtaining real IP for trusted IP list: unable to get ip and port from http.RemoteAddr (@)
```

### Changes

- **`pkg/ip/realclientip.go` — `getRemoteIP`**: Return `nil, nil` for `"@"` RemoteAddr since Unix sockets have no meaningful client IP. This is the root fix — all callers (`isTrustedIP`, `GetClientString`, etc.) benefit.
- **`pkg/ip/realclientip.go` — `GetClientString`**: Add nil check before calling `String()` on the returned `net.IP`, preventing `"<nil>"` appearing as the client string for socket connections.
- **`oauthproxy.go` — `isTrustedIP`**: Simplify the guard — if `trustedIPs` is nil, return false unconditionally. The previous `req.RemoteAddr != "@"` check was meant to handle sockets but had inverted logic (it prevented the early return for socket connections, causing them to fall through into the broken path).

### Why the old logic was wrong

The guard `p.trustedIPs == nil && req.RemoteAddr != "@"` evaluated to `false` for socket connections (since `"@" != "@"` is `false`), so the function skipped the early return and fell through to `GetClientIP` → `getRemoteIP` → `SplitHostPort("@")` → error on every request.

## Test plan

- [x] Added `"@"` test case to `TestGetRemoteIP` — verifies `nil, nil` return
- [x] Added Unix socket test case to `TestGetClientString` — verifies empty string, not `"<nil>"`
- [x] Added `UnixSocketWithoutTrustedIPs` to `TestTrustedIPs` — verifies no error when trustedIPs is nil
- [x] Added `UnixSocketWithTrustedIPs` to `TestTrustedIPs` — verifies false when trustedIPs is set but no IP available
- [x] All existing tests pass

### CODE REVIEW

File: pkg/ip/realclientip.go [hunk 1]
```diff
@@ -73,6 +73,12 @@ func GetClientIP(p ipapi.RealClientIPParser, req *http.Request) (net.IP, error)
 
 // getRemoteIP obtains the IP of the low-level connected network host
 func getRemoteIP(req *http.Request) (net.IP, error) {
+	// Unix domain sockets set RemoteAddr to "@" which has no meaningful IP.
+	// https://github.com/golang/go/blob/0fa53e41f122b1661d0678a6d36d71b7b5ad031d/src/syscall/syscall_linux.go#L506-L511
```
Comment (tuunit) [inline pkg/ip/realclientip.go:77]: Great thanks for moving the resource!

File: oauthproxy_test.go [hunk 2]
```diff
@@ -2149,6 +2149,32 @@ func TestTrustedIPs(t *testing.T) {
 			}(),
 			expectTrusted: false,
 		},
+		// Check Unix socket with no trusted IPs configured does not error.
```
Comment (tuunit) [inline oauthproxy_test.go:2153]: So does this mean the contents of trusted ips for unix sockets will now be fully ignored/skipped? We should add that to the docs

**Review by tuunit — CHANGES_REQUESTED** [review]
Seems like a reasonable fix. 

* Please add a changelog entry
* Sign-off your commits (https://github.com/apps/dco)

**Comment by H1net** [comment]
Thanks for the review! I've addressed both points:

- Added a changelog entry
- Added a "Trusted IPs" section to the systemd socket docs explaining that `--trusted-ip` can't match against `RemoteAddr` for socket listeners (since Go sets it to `"@"`), but that IP-based trust still works via `X-Forwarded-For` / `X-Real-IP` with `--reverse-proxy=true`
- Signed off commits and rebased on master

Let me know if the docs wording needs tweaking.
