### PR TITLE
fix: use GetSecret() in ticket.go makeCookie to respect cookie-secret-file

### LINKED ISSUE #3224: cookie_secret_file option fails when validating cookies
Cookie signing was not converted to use `options.GetSecret()`

https://github.com/oauth2-proxy/oauth2-proxy/blob/dc8b1623a26a2537a8d0119e087f2048234c9843/pkg/sessions/persistence/ticket.go#L237-L237

### PR DESCRIPTION
**Pull request by stagswtf**
The makeCookie method in ticket.go was using t.options.Secret directly, which meant cookie-secret-file was not being respected. Updated to use GetSecret() which handles both cookie-secret and cookie-secret-file properly.

Also added test coverage for cookie-secret-file functionality.

Fixes #3224

## Description

The `makeCookie` method in `ticket.go` was directly accessing `t.options.Secret` when signing cookie values. This meant that when users configured a `cookie-secret-file`, the secret from the file was not being used. 

Changes made:
- Updated `makeCookie` to use `t.options.GetSecret()` which properly handles both `cookie-secret` and `cookie-secret-file`
- Added test coverage in `session_store_tests.go` to verify cookie signing works with secrets loaded from files

## Motivation and Context

When users configure oauth2-proxy with `cookie-secret-file`, they expect the secret from that file to be used for all cookie operations. However, due to this bug, the `makeCookie` method was bypassing the file-based secret mechanism and only using the direct secret value.

This fixes issue #3224 where it was reported that cookie signing was broken when using `cookie-secret-file`.

## How Has This Been Tested?

- Added a new test context "with cookie secret file" to the session store test suite
- Test creates a temporary file with a random 32-byte secret
- Verifies that session store operations work correctly when using only `cookie-secret-file` (with empty `Secret`)
- All existing tests continue to pass with no modifications needed
- Ran the full test suite with Go 1.24.6 on Linux

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.
- [x] I have written tests for my code changes.

### CODE REVIEW

**Comment by stagswtf** [comment]
I think I am done here, but let me know.

**Comment by stagswtf** [comment]
How do i make the build step happen?

**Comment by pixeldrew** [comment]
Need this fix. Docker compose secrets not working if you want your cookie secret as a docker secret

File: pkg/sessions/persistence/ticket.go [hunk 1]
```diff
@@ -233,8 +233,11 @@ func (t *ticket) clearCookie(rw http.ResponseWriter, req *http.Request) {
 // makeCookie makes a cookie, signing the value if present
 func (t *ticket) makeCookie(req *http.Request, value string, expires time.Duration, now time.Time) (*http.Cookie, error) {
 	if value != "" {
-		var err error
-		value, err = encryption.SignedValue(t.options.Secret, t.options.Name, []byte(value), now)
+		secret, err := t.options.GetSecret()
+		if err != nil {
+			return nil, err
```
Comment (tuunit) [inline pkg/sessions/persistence/ticket.go]: Please wrap the error

```suggestion
			return nil, fmt.Errorf("retrieving secret failed: %w", err)
```
