### PR TITLE
Watch the `htpasswd` file for changes and update the `htpasswdMap`

### LINKED ISSUE #1320: Need to allow oauth2-proxy to allow watching the changes in the content behind htpasswd-file
We want to be able to make oauth2-proxy watch the values from the `htpasswd-file` and dynamically allow them new entries to be picked-up/removed. Similar to what `authenticated-emails-file` flag is doing. 

## Expected Behavior

Adding a new user/password entry in the storage (secret) behind the `htpasswd-file` will allow the new user to login. Removing an entry from storage will deny that user a successful login.

## Current Behavior

Currently the updates in the content of `htpasswd-file` and not picked-up by oauth2-proxy authentication mechanism.

## Possible Solution

Similar implementation with what is behind the `authenticated-emails-file` flag.

## Steps to Reproduce (for bugs)

1. Start oauth2-proxy with `display-htpasswd-form` and `htpasswd-file`
2. Add a new entry in the secret holding the list of existing users/passwords
3. Attempt a login with the newly introduced credentials
4. Login fails

## Context

There are some scenarios (PoCs, local installs, ...) where we use the `htpasswd-file` to authenticate users and our solution needs a dynamic way in adding new users that can access the solution.

## Your Environment

Not relevant, 

- Version used: v7.1.3

### PR DESCRIPTION
**Pull request by aiciobanu**
## Description

 - `watcher.go` was moved to a package to be accessible globally
 - `watcher.go` - code was refactored to accommodate the implemented feature
 - `htpasswd.go` - code was refactored to allow updates while the service is up&running
 - `htpasswd_test.go` - new tests were added to validate the added feature

Based on these changes basic auth users can be dynamically added or removed

 ## Motivation and Context

Fixes #1320

## How Has This Been Tested?

 - Unit tests
 - Local Kubernetes environment:
    - deployed the `oauth2-proxy` chart
    - made changes to the `htpasswd-file` `Secret` while the service was running (used working/malformed/invalid user details)
    - tested the login based on different existing/non-existing user details

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

File: pkg/watcher/watcher.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+
+	"github.com/oauth2-proxy/oauth2-proxy/v7/pkg/logger"
+)
+
+// WatchForUpdates performs an action every time a file on disk is updated
+func WatchFileForUpdates(filename string, done <-chan bool, action func()) {
+	filename = filepath.Clean(filename)
+	watcher, err := fsnotify.NewWatcher()
+	if err != nil {
+		logger.Fatalf("failed to create watcher for '%s': %s", filename, err)
```
Comment (braunsonm) [inline pkg/watcher/watcher.go:18]: Similar comment to before, I think this is a bad practice to not return an error instead.

File: pkg/watcher/watcher.go [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+		defer watcher.Close()
+
+		for {
+			select {
+			case <-done:
+				logger.Printf("shutting down watcher for: %s", filename)
+				return
+			case event, ok := <-watcher.Events:
+				if !ok { // 'Events' channel is closed
+					logger.Errorf("error: cannot start the watcher, events channel is closed")
```
Comment (braunsonm) [inline pkg/watcher/watcher.go:31]: What does this mean to a user?

File: pkg/watcher/watcher.go [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+		logger.Fatalf("failed to create watcher for '%s': %s", filename, err)
+	}
+
+	go func() {
+		defer watcher.Close()
+
+		for {
+			select {
+			case <-done:
+				logger.Printf("shutting down watcher for: %s", filename)
```
Comment (braunsonm) [inline pkg/watcher/watcher.go:27]: do we need to log this?

File: pkg/authentication/basic/htpasswd.go [hunk 4]
```diff
@@ -30,59 +33,111 @@ type sha1Pass string
...
-	csvReader := csv.NewReader(file)
+	csvReader := csv.NewReader(r)
 	csvReader.Comma = ':'
 	csvReader.Comment = '#'
 	csvReader.TrimLeadingSpace = true
 
 	records, err := csvReader.ReadAll()
 	if err != nil {
-		return nil, fmt.Errorf("could not read htpasswd file: %v", err)
+		logger.Fatalf("could not read htpasswd file: %v", err)
```
Comment (braunsonm) [inline pkg/authentication/basic/htpasswd.go:74]: Why did you decide to close here instead of propagating this error up? I think it's better that sub functions not concern themselves with exiting the program at errors, they don't understand the full context of what the system might do to retry.

File: pkg/authentication/basic/htpasswd.go [hunk 5]
```diff
@@ -30,59 +33,111 @@ type sha1Pass string
...
+
+	if len(invalidEntries) > 0 {
+		return h, fmt.Errorf("'%+q' user(s) could not be added: invalid password, must be a SHA or bcrypt entry", invalidEntries)
+	}
 
-		// Password is neither sha1 or bcrypt
-		// TODO(JoelSpeed): In the next breaking release, make this return an error.
-		logger.Errorf("Invalid htpasswd entry for %s. Must be a SHA or bcrypt entry.", user)
+	if len(h.users) == 0 {
+		logger.Fatal("could not construct htpasswdMap: htpasswd file doesn't contain a single valid user entry")
```
Comment (braunsonm) [inline pkg/authentication/basic/htpasswd.go:115]: fatal, propagate this error up

File: pkg/authentication/basic/htpasswd.go [hunk 6]
```diff
@@ -30,59 +33,111 @@ type sha1Pass string
...
 
+// passShaOrBcrypt checks if a htpasswd entry is valid and the password is encrypted with SHA or bcrypt.
+// Valid user entries are saved in the htpasswdMap, invalid records are reurned.
+func passShaOrBcrypt(h *htpasswdMap, user, password string) (invalidEntries []string) {
+	passLen := len(password)
+	switch {
+	case passLen > 6 && password[:5] == "{SHA}":
+		h.users[user] = sha1Pass(password[5:])
+	case passLen > 5 &&
+		(password[:4] == "$2b$" ||
```
Comment (braunsonm) [inline pkg/authentication/basic/htpasswd.go:129]: Is this gofmted? looks a bit odd formatting here.

File: pkg/authentication/basic/htpasswd_test.go [hunk 7]
```diff
@@ -91,6 +93,71 @@ var _ = Describe("HTPasswd Suite", func() {
...
+
+					err = file.Close()
+					Expect(err).ToNot(HaveOccurred())
+
+					fileNames = append(fileNames, file.Name())
+
+					return htpasswd
+				}
+
+				htpasswdAdd := htpasswdMap(adminUserHtpasswdEntry, user1HtpasswdEntry, false)
```
Comment (braunsonm) [inline pkg/authentication/basic/htpasswd_test.go:146]: These should be inside the `It`

File: pkg/watcher/watcher.go [hunk 8]
```diff
@@ -0,0 +1,82 @@
...
+	switch filepath.Clean(event.Name) == filename {
+	case event.Op&(fsnotify.Remove|fsnotify.Rename) != 0:
+		logger.Printf("watching interrupted on event: %s", event)
+		WaitForReplacement(filename, event.Op, watcher)
+		action()
+	case event.Op&(fsnotify.Create|fsnotify.Write) != 0:
+		logger.Printf("reloading after event: %s", event)
+		action()
+	default:
+		logger.Printf("current event: %s", event)
```
Comment (braunsonm) [inline pkg/watcher/watcher.go:60]: Probably don't need to log this

File: pkg/watcher/watcher.go [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+	if err = watcher.Add(filename); err != nil {
+		logger.Fatalf("failed to add '%s' to watcher: %v", filename, err)
+	}
+	logger.Printf("watching '%s' for updates", filename)
+}
+
+// Filter file operations based on the events sent by the watcher.
+// Execute the action() function when the following conditions are met:
+//  - the file is modified or created
+//  - the real path of the file was changed (Kubernetes ConfigMap/Secret)
```
Comment (braunsonm) [inline pkg/watcher/watcher.go:49]: Is this the Remove/Rename steps specifically?

File: pkg/watcher/watcher.go (hunk 1 above)
Comment (aiciobanu) [reply pkg/watcher/watcher.go:18]: Error returned.

File: pkg/watcher/watcher.go (hunk 3 above)
Comment (aiciobanu) [reply pkg/watcher/watcher.go:27]: Yes,`done` is user specified. It can be closed whenever someone explicitly configured it, thus it should be clear in the logs that the action was completed.

File: pkg/authentication/basic/htpasswd.go (hunk 5 above)
Comment (aiciobanu) [reply pkg/authentication/basic/htpasswd.go:115]: Error returned.

File: pkg/authentication/basic/htpasswd.go (hunk 6 above)
Comment (aiciobanu) [reply pkg/authentication/basic/htpasswd.go:129]: Yes.

image

**Comment by tlawrie** [comment]
Hi all. Checking into this PR to see if its now ready for merge?

**Comment by aiciobanu** [comment]
@braunsonm The requested changes were implemented, could you please review it again?

**Review by braunsonm — DISMISSED** [review]
lgtm, @JoelSpeed

File: pkg/authentication/basic/htpasswd.go [hunk 10]
```diff
@@ -30,59 +33,114 @@ type sha1Pass string
 // NewHTPasswdValidator constructs an httpasswd based validator from the file
 // at the path given.
 func NewHTPasswdValidator(path string) (Validator, error) {
+	h := &htpasswdMap{users: make(map[string]interface{})}
+
+	err := h.loadHTPasswdFile(path)
+	if err != nil {
```
Comment (JoelSpeed) [inline pkg/authentication/basic/htpasswd.go:39]: It's idiomatic to inline this
```suggestion
	if err := h.loadHTPasswdFile(path); err != nil {
```

File: pkg/authentication/basic/htpasswd.go [hunk 11]
```diff
@@ -30,59 +33,114 @@ type sha1Pass string
...
+		return nil, err
+	}
+
+	err = watcher.WatchFileForUpdates(path, nil, func() {
+		err := h.loadHTPasswdFile(path)
+		if err != nil {
+			logger.Errorf("%v: no changes were made to the current htpasswd map", err)
+		}
+	})
+	if err != nil {
```
Comment (JoelSpeed) [inline pkg/authentication/basic/htpasswd.go:49]:
```suggestion
	if err := watcher.WatchFileForUpdates(path, nil, func() {
		err := h.loadHTPasswdFile(path)
		if err != nil {
			logger.Errorf("%v: no changes were made to the current htpasswd map", err)
		}
	});  err != nil {
```

File: pkg/authentication/basic/htpasswd.go [hunk 12]
```diff
@@ -30,59 +33,114 @@ type sha1Pass string
 // NewHTPasswdValidator constructs an httpasswd based validator from the file
 // at the path given.
 func NewHTPasswdValidator(path string) (Validator, error) {
+	h := &htpasswdMap{users: make(map[string]interface{})}
+
+	err := h.loadHTPasswdFile(path)
+	if err != nil {
+		return nil, err
```
Comment (JoelSpeed) [inline pkg/authentication/basic/htpasswd.go:40]: Please wrap errors you are returning with additional context
```suggestion
		return nil, fmt.Errorf("could not load htpasswd file: %v", err)
```

File: pkg/authentication/basic/htpasswd.go [hunk 13]
```diff
@@ -30,59 +33,114 @@ type sha1Pass string
...
+	}
+
+	err = watcher.WatchFileForUpdates(path, nil, func() {
+		err := h.loadHTPasswdFile(path)
+		if err != nil {
+			logger.Errorf("%v: no changes were made to the current htpasswd map", err)
+		}
+	})
+	if err != nil {
+		return nil, err
```
Comment (JoelSpeed) [inline pkg/authentication/basic/htpasswd.go:50]: Please wrap with context

File: pkg/watcher/watcher.go [hunk 14]
```diff
@@ -0,0 +1,81 @@
...
+				logger.Printf("shutting down watcher for: %s", filename)
+				return
+			case event := <-watcher.Events:
+				filterEvent(watcher, event, filename, action)
+			case err = <-watcher.Errors:
+				logger.Errorf("error watching '%s': %s", filename, err)
+			}
+		}
+	}()
+	if err = watcher.Add(filename); err != nil {
```
Comment (JoelSpeed) [inline pkg/watcher/watcher.go:37]: Nit, dont shadow variables when we don't have to
```suggestion
	if err := watcher.Add(filename); err != nil {
```

**Review by JoelSpeed — COMMENTED** [review]
Some styling nits but otherwise LGTM, thanks!

File: pkg/authentication/basic/htpasswd.go (hunk 12 above)
Comment (aiciobanu) [reply pkg/authentication/basic/htpasswd.go:39]: We already have the context in the `oauthproxy.go` file -> https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L114-L117.
We just need the value of the error retrieved from `loadHTPasswdFile` or `WatchFileForUpdates`.

File: pkg/authentication/basic/htpasswd.go (hunk 13 above)
Comment (aiciobanu) [reply pkg/authentication/basic/htpasswd.go:48]: The context in already in the `oauthproxy.go` file -- same as above.

File: pkg/authentication/basic/htpasswd.go (hunk 12 above)
Comment (aiciobanu) [reply pkg/authentication/basic/htpasswd.go]: Changed the error message from `oauthproxy.go` and added the context for load and watch.

File: pkg/authentication/basic/htpasswd.go (hunk 13 above)
Comment (aiciobanu) [reply pkg/authentication/basic/htpasswd.go]: Wrapped the error with context

**Review by JoelSpeed — APPROVED** [review]
Great, let's get this merged!

**Comment by tlawrie** [comment]
Amazing!
