### PR TITLE
Validate and log provider type on startup

### LINKED ISSUE #895: Specifying non-existent provider causes unexpected and unannounced default to "Google"
Most of the conversation is in this thread: https://github.com/oauth2-proxy/oauth2-proxy/pull/886#discussion_r516452077

Specifying a non-existing provider or making a typo in provider name currently results in a silent default to provider "google".
This causes unexpected and undesirable behavior.

Desired behavior:
1. Announce selected provider in the logs on startup.
2. Fail if a non-existent provider is requested - do not default.

### PR DESCRIPTION
**Pull request by arcivanov**
Logs provider name on startup
If invalid provider is specified, stop and error out

fixes #895

- [X] My change requires a change to the documentation or CHANGELOG.
- [X] I have updated the documentation/CHANGELOG accordingly.
- [X] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

File: pkg/validation/options.go [hunk 1]
```diff
@@ -233,7 +233,14 @@ func parseProviderInfo(o *options.Options, msgs []string) []string {
 	p.ValidateURL, msgs = parseURL(o.ValidateURL, "validate", msgs)
 	p.ProtectedResource, msgs = parseURL(o.ProtectedResource, "resource", msgs)
 
-	o.SetProvider(providers.New(o.ProviderType, p))
+	provider := providers.New(o.ProviderType, p)
+	if provider == nil {
+		msgs = append(msgs, fmt.Sprintf("invalid setting: provider '%s' is not available", o.ProviderType))
+		return msgs
+	}
+	logger.Printf("configuring provider '%s'", o.ProviderType)
```
Comment (JoelSpeed) [inline pkg/validation/options.go:241]: We already log this in the core of the project so we don't need to log it here as well

https://github.com/oauth2-proxy/oauth2-proxy/blob/6254ed24ea319302b8cbdd8aaa16f6495c0b4c11/oauthproxy.go#L140

File: providers/providers.go [hunk 2]
```diff
@@ -46,7 +46,9 @@ func New(provider string, p *ProviderData) Provider {
 		return NewNextcloudProvider(p)
 	case "digitalocean":
 		return NewDigitalOceanProvider(p)
-	default:
+	case "google":
 		return NewGoogleProvider(p)
+	default:
+		return nil
```
Comment (JoelSpeed) [inline providers/providers.go:52]: This is a breaking change, we will need to highlight this in the changelog.

Some users may be implicitly using the google provider unknowingly. We need to make a note that the default has changed from `google` to an error and that to retain existing behaviour, if a user hasn't set their provider, to set it to `google`

File: CHANGELOG.md [hunk 3]
```diff
@@ -4,6 +4,7 @@
 
 ## Important Notes
 
+- [#895](https://github.com/oauth2-proxy/oauth2-rpoxy/pull/895)/[#911](https://github.com/oauth2-proxy/oauth2-rpoxy/pull/911) Validate and log provider type on startup.
```
Comment (JoelSpeed) [inline CHANGELOG.md:7]: We only link to the PR normally, any additional discussion is normally linked from there
```suggestion
- [#911](https://github.com/oauth2-proxy/oauth2-proxy/pull/911) Validate and log provider type on startup.
```

**Review by JoelSpeed — COMMENTED** [review]
I hadn't seen the thread of the discussion about this issue, but I agree this improves the UX. Please see my comments inline

File: pkg/validation/options.go (hunk 1 above)
Comment (arcivanov) [reply pkg/validation/options.go:241]: Ok, wil remove

File: providers/providers.go (hunk 2 above)
Comment (arcivanov) [reply providers/providers.go:52]: No, it's not, we still default to "google": https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/apis/options/options.go#L137

**Comment by arcivanov** [comment]
> I hadn't seen the thread of the discussion about this issue, but I agree this improves the UX. Please see my comments inline

The thread of discussion was here: https://github.com/oauth2-proxy/oauth2-proxy/pull/886#pullrequestreview-522208160

File: providers/providers.go (hunk 2 above)
Comment (arcivanov) [reply providers/providers.go:52]: Also this: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/apis/options/options.go#L219

File: CHANGELOG.md (hunk 3 above)
Comment (arcivanov) [reply CHANGELOG.md:7]: Will fix.

Comment (arcivanov) [reply CHANGELOG.md]: Fixed.

File: pkg/validation/options.go (hunk 1 above)
Comment (arcivanov) [reply pkg/validation/options.go]: Fixed.

File: providers/providers.go (hunk 2 above)
Comment (NickMeves) [reply providers/providers.go:52]: It is still breaking, we just need to make a note.

The default is `google` (which this doesn't change). But the unknown case reverts to `google` -- this will change that.

Gotta warn our users who misspelled `google` as `goggle` 😄

Comment (arcivanov) [reply providers/providers.go:52]: Ah, that's what you meant. Will update the doc.

Comment (arcivanov) [reply providers/providers.go:52]: Fixed.

**Comment by arcivanov** [comment]
@JoelSpeed No clue why the test is suddenly failing as I didn't change any code. Can't rerun the test, unfortunately.

File: CHANGELOG.md [hunk 4]
```diff
@@ -4,6 +4,7 @@
 
 ## Important Notes
 
+- [#911](https://github.com/oauth2-proxy/oauth2-rpoxy/pull/911) Validate provider type on startup.
```
Comment (JoelSpeed) [inline CHANGELOG.md:7]: Can we move this to the change since v6.1.1 section please? Having it in breaking is good enough additional highlighting, but all changes should be in changes since v6.1.1

Comment (arcivanov) [reply CHANGELOG.md]: Sure :)

**Comment by JoelSpeed** [comment]
Test failure was just a flake, don't worry about it. 

Just one change for the changelog file and then I'm happy to merge, thanks for working on this!

File: CHANGELOG.md (hunk 4 above)
Comment (arcivanov) [reply CHANGELOG.md]: Fixed.

**Comment by arcivanov** [comment]
@JoelSpeed Done.
