### PR TITLE
Fix upstream proxy appending `?` to requests

### LINKED ISSUE #1112: Upstream path error when path end with ? character
The proxy send request to upstream server with wrong path when path end withs `?`
For example, the original request `https://proxy-domain.url/file/count?`
The request sent to upstream by oauth2-proxy is `http://upstream-server/file/count??`

## Expected Behavior

The path should be `file/count?` instead of `file/count??`

## Current Behavior

The path is `file/count??`

- Version used: `7.0.1`

### PR DESCRIPTION
**Pull request by JoelSpeed**
## Description

Overwrite force query in the proxy director to prevent it appending a `?` to every request that ends with `?`

## Motivation and Context

When a URL is parsed, if it ends with `?`, the URL gets the force query param set.
When the string is converted back to a string, if force query is set, then a `?` is added to the end no matter what the query string is.

Since we use the opaque request in the director and overwrite the query (to prevent it being appended), we also need to set force query to false.

Fixes #1112 

## How Has This Been Tested?

Unit tests and local testing environment

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

File: pkg/upstream/http.go [hunk 1]
```diff
@@ -153,6 +153,7 @@ func setProxyDirector(proxy *httputil.ReverseProxy) {
 		// use RequestURI so that we aren't unescaping encoded slashes in the request path
 		req.URL.Opaque = req.RequestURI
 		req.URL.RawQuery = ""
+		req.URL.ForceQuery = false
```
Comment (NickMeves) [inline pkg/upstream/http.go:156]: Is this needed in `setProxyUpstreamHostHeader` too?

Comment (NickMeves) [reply pkg/upstream/http.go:156]: Out of curiosity, where is this getting set to `true` before this point?

Comment (JoelSpeed) [reply pkg/upstream/http.go:156]: Good catch! Yes it will want to be set there too! In fact, tbh, looking at this, the whole point of these is that they are meant to be chained, let me rework this a bit

**Comment by JoelSpeed** [comment]
@NickMeves This should now be ready to go, I've rearranged the proxy directors so we no longer have duplication. We have checks in place that the host header redirection is working in both cases now via separate tests

**Review by NickMeves — APPROVED** [review]
LGTM! Good refactor of the split logic to chain instead 👍

**Comment by JoelSpeed** [comment]
Rebased to fix changelog conflict, not other changes, will merge once green
