### PR TITLE
Fix #635: Support specifying alternative provider TLS trust source(s)

### LINKED ISSUE #635: Specifying alternative provider TLS trust source(s) from command line or config.
For my use-case, the OIDC provider in use may use a server-cert signed by private CA that may not be trusted by the default SystemCertPool.

It is possible to specify the `SSL_CERT_DIR` environment variable, as this currently supports only a single directory, it means you need to use a script to centralise all the required trust (upstream, provider) into a single directory.    This works but is inconvenient, especially if the trust is projected from config maps in the Kubernetes world.  

## Expected Behavior

It'd be useful is the oauthproxy accepted additional trust source(s) perhaps from a command line/conig option,`--cacert`  (borrowing arg name from from cURL) to specify an additional file(s) to add to the pool.

## Current Behavior

As described above

## Possible Solution

As described above

## Steps to Reproduce (for bugs)

-
## Your Environment

- Version used:

### PR DESCRIPTION
**Pull request by k-wall**
## Description

Support a new flag `--provider-ca-file` that allows the user to specify sources of trusts for TLS interactions with the OIDC provider.  Some. of the code is based on previous work from OpenShift oauth-proxy authors.

## Motivation and Context

As discussed in #635.

## How Has This Been Tested?

Existing unit test suite passes.
Added unit test for the new util package.

Also, manually tested oauth2-proxy command with and without the new flag.

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

File: pkg/apis/options/options.go [hunk 1]
```diff
@@ -85,22 +85,23 @@ type Options struct {
...
-	ProfileURL                         string `flag:"profile-url" cfg:"profile_url"`
-	ProtectedResource                  string `flag:"resource" cfg:"resource"`
-	ValidateURL                        string `flag:"validate-url" cfg:"validate_url"`
-	Scope                              string `flag:"scope" cfg:"scope"`
-	Prompt                             string `flag:"prompt" cfg:"prompt"`
-	ApprovalPrompt                     string `flag:"approval-prompt" cfg:"approval_prompt"` // Deprecated by OIDC 1.0
-	UserIDClaim                        string `flag:"user-id-claim" cfg:"user_id_claim"`
+	ProviderType                       string   `flag:"provider" cfg:"provider"`
+	ProviderName                       string   `flag:"provider-display-name" cfg:"provider_display_name"`
+	ProviderCAFiles                    []string `flag:"provider-ca-file" cfg:"provider_ca_file"`
```
Comment (JoelSpeed) [inline pkg/apis/options/options.go:90]: When this is in the configuration file, it should be pluralised, so this should be 
```suggestion
	ProviderCAFiles                    []string `flag:"provider-ca-file" cfg:"provider_ca_files"`
```

File: pkg/util/util_test.go [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+	"io/ioutil"
+	"os"
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+)
+
+var (
+	testCA1Subj = "301e311c301a060355040313136f617574682d70726f78792074657374206361"
+	testCA1     = `-----BEGIN CERTIFICATE-----
```
Comment (JoelSpeed) [inline pkg/util/util_test.go:14]: I wonder if there's a way we can generate certificates in memory, easily, during the testing so that we don't have to commit certificates into the tests.

Out of interest, how did you create this certificate?

File: pkg/validation/options.go [hunk 3]
```diff
@@ -13,6 +13,8 @@ import (
 	"sort"
 	"strings"
 
+	"github.com/oauth2-proxy/oauth2-proxy/pkg/util"
+
```
Comment (JoelSpeed) [inline pkg/validation/options.go:17]: I don't think we need this new line here

File: pkg/validation/options.go [hunk 4]
```diff
@@ -28,11 +30,22 @@ import (
 // are of the correct format
 func Validate(o *options.Options) error {
 	if o.SSLInsecureSkipVerify {
-		// TODO: Accept a certificate bundle.
 		insecureTransport := &http.Transport{
 			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
 		}
 		http.DefaultClient = &http.Client{Transport: insecureTransport}
+	} else if o.ProviderCAFiles != nil && len(o.ProviderCAFiles) > 0 {
```
Comment (JoelSpeed) [inline pkg/validation/options.go:37]: Is `ProviderCAFiles` a pointer? I didn't think it was? We shouldn't need the `!= nil` check here I don't think

File: pkg/validation/options.go [hunk 5]
```diff
@@ -28,11 +30,22 @@ import (
...
+		pool, err := util.GetCertPool(o.ProviderCAFiles)
+		if err != nil {
+			return err
```
Comment (JoelSpeed) [inline pkg/validation/options.go:40]: Maybe we should wrap this to add more context
```suggestion
			return fmt.Errorf("unable to load provider CA file(s): %v", err)
```

Also, this method is meant to collate all of the possible errors and then return them as a single error at the end, can we make sure we retain that behaviour please

File: pkg/validation/options.go (hunk 3 above)
Comment (k-wall) [reply pkg/validation/options.go:17]: Done.

File: pkg/validation/options.go (hunk 4 above)
Comment (k-wall) [reply pkg/validation/options.go:37]: It is not a pointer, `!=` removed.

File: pkg/util/util_test.go (hunk 2 above)
Comment (k-wall) [reply pkg/util/util_test.go:14]: If I were to generate the certificate, this would bring a heap of crypto/x509 and encoding/pem noise to the test.  I think this might be worse than the inline string.   I'm happy to take the generation route if preferred.  The implementation of the test and the test data came from: https://github.com/openshift/oauth-proxy/commit/b3380fc94a13616549cede5e3841d09d371473f3.    The original GetCertPool implementation came from the same project.

Comment (JoelSpeed) [reply pkg/util/util_test.go:14]: I would love to have a comment that explains how these were made, or at least, how we could regenerate some if we ever wanted to change them, don't suppose you happen to know?

Comment (k-wall) [reply pkg/util/util_test.go:18]: I've added the OpenSsl command used to generate the certificate test data to test.  I also changed the test to assert the contents of the pool based in subject names (textual) which tallies with the `-subj` command.
