### PR TITLE
fix: invalidate session on fatal OAuth2 refresh errors

### LINKED ISSUE #1945: Stop attempting to refresh access token for session if receiving "Session not active"
## Expected Behavior

Enhancement request: oauth2-proxy should stop attempting to refresh the session after receiving  `Response: {"error":"invalid_grant","error_description":"Session not active"}`

## Current Behavior

oauth2-proxy is configured with `cookie_refresh` and successfully refreshes the session cookie when the provider's session is active. When the session is not active, oauth2-proxy attempts to refresh the session about five times every two seconds and correctly gets the following error:
```
oauth2-proxy    | [2022/12/21 03:00:13] [stored_session.go:94] Error loading cookied session: error refreshing access token for session (Session{email:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx user:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx PreferredUsername:xxxx token:true id_token:true created:2022-12-21 02:54:44.27982877 +0000 UTC expires:2022-12-21 02:55:44.268840644 +0000 UTC refresh_token:true}): session is expired, removing session
oauth2-proxy    | [2022/12/21 03:00:13] [stored_session.go:193] Unable to refresh session: error refreshing tokens: unable to redeem refresh token: failed to get token: oauth2: cannot fetch token: 400 Bad Request
oauth2-proxy    | Response: {"error":"invalid_grant","error_description":"Session not active"}
```

## Possible Solution

Stop attempting to refresh the session after receiving  `Response: {"error":"invalid_grant","error_description":"Session not active"}` 

## Steps to Reproduce (for bugs)

1.  Set oauth2-proxy `cookie_refresh` to some value (mine is 5m)
2. Trigger provider session expiry
3. oauth2-proxy attempts to refresh cookie, gets provider response that the session expired
4. oauth2-proxy keeps attempting to refresh cookie for the expired session

## Context

The issue creates many unnecessary requests

## Your Environment

Docker internal network 

- Version used:
`Linux 5.4.0-135-generic` `Docker version 20.10.12` `nginx/1.22.1` `Keycloak 20.0.2` `oauth2-proxy:v7.4.0`

### PR DESCRIPTION
**Pull request by frhack**
## Summary

Fixes #1945

When a token refresh fails with a fatal OAuth2 error (`invalid_grant`, `invalid_client`), the session is now cleared from the session store and the cookie is removed, forcing re-authentication.

Previously, fatal refresh errors were logged but the stale session continued to be served indefinitely.

## Changes

- Added `isFatalRefreshError()` helper in `pkg/middleware/stored_session.go` that checks for standard OAuth2 error codes (RFC 6749 Section 5.2)
- Modified `refreshSessionIfNeeded()` to call `store.Clear()` on fatal errors
- Added unit tests for the new helper function

## Behavior

| Error type | Before | After |
|------------|--------|-------|
| `invalid_grant` (session revoked) | Logged, session kept | Session cleared, redirect to login |
| `invalid_client` (client invalid) | Logged, session kept | Session cleared, redirect to login |
| Network timeout | Logged, session kept | Logged, session kept (unchanged) |
| Server 5xx | Logged, session kept | Logged, session kept (unchanged) |

## Testing

- Unit tests added for `isFatalRefreshError()`
- All existing tests pass (162/162)
- Tested in production with Keycloak 26 + Redis session store + `cookie-refresh` enabled

## Notes

Only standard OAuth2 error codes are checked (not provider-specific `error_description` strings), as `error_description` is optional per RFC 6749.

### CODE REVIEW

**Comment by smoothscholar** [comment]
@tuunit  @frhack I am experiencing similar keycloak REFRESH_TOKEN_ERROR in my setup, but my issue seems to be in the opposite direction. Oauth2 proxy is encountering this issue too frequently and blocking access to my backend services until user fully reloads the page. Is this PR related to my issue? Would appreciate any assistance diagnosing the behavior I am seeing: #3402

File: pkg/middleware/stored_session.go [hunk 1]
```diff
@@ -188,9 +217,25 @@ func (s *storedSessionLoader) refreshSessionIfNeeded(rw http.ResponseWriter, req
...
+		// Check if this is a fatal error that indicates the session is revoked
+		// or no longer valid at the provider level
+		if isFatalRefreshError(err) {
+			logger.Printf("Fatal refresh error detected (session revoked or invalid), clearing session for user: %s", session.User)
+
+			// Clear the session from storage (Redis) and remove the cookie
+			clearErr := s.store.Clear(rw, req)
+			if clearErr != nil {
+				logger.Errorf("Error clearing session: %v", clearErr)
+			}
```
Comment (tuunit) [inline pkg/middleware/stored_session.go]:
```suggestion
			if err := s.store.Clear(rw, req); err != nil {
				logger.Errorf("failed clearing session: %v", err)
			}
```

File: pkg/middleware/stored_session.go [hunk 2]
```diff
@@ -31,6 +32,34 @@ const (
...
+		"invalid_client", // client credentials no longer valid
+	}
+
+	for _, fe := range fatalErrors {
+		if strings.Contains(errStr, fe) {
+			return true
+		}
+	}
+	return false
+}
```
Comment (tuunit) [inline pkg/middleware/stored_session.go]:
```suggestion
	// Only check standard OAuth2 error codes (RFC 6749 Section 5.2)
	// Do NOT check error_description strings as they are optional and provider-specific
	fatalErrors := []string{
		"invalid_grant",  // refresh token revoked, expired, or session terminated
		"invalid_client", // client credentials no longer valid
	}

	for _, fe := range fatalErrors {
		if strings.Contains(err.Error(), fe) {
			return true
		}
	}
	return false
}
```
