### PR TITLE
Reinstate preferEmailToUser behaviour for basic auth sessions

### LINKED ISSUE #1079: oauth2-proxy 7.0.1 fails when mixing Oauth2 users and htaccess users
## Expected Behavior

For various reasons we have authentication using oauth2-proxy that mixes htaccess logins and oauth2 logins. 

In 6.1.1  and before the proxy would generate an Authorization Basic header with either the htaccess username, or the oauth2 username (or email claim), both with the same defaulted password from the setting.

This means that no matter which access method was used to get a claim, the Authorization header passed to the  web application would match with a username  and static password.

## Current Behavior

The current behaviour instead ONLY generates the Authorization: Basic  header for oauth2 logins, and simply doesn't pass the  oauth2-enabled htaccess login names at all to the backend.  This also seems to be the case for the HTTP headers when using side-by-side authentication.

## Possible Solution

Consider adding the oauth2 managed htaccess usernames and treating them as usernames.

## Steps to Reproduce (for bugs)

Simply upgrading to version 7.x  was enough to change this behaviour and break our monitoring and authentication flow. It should be noted that the /oauth2/userinfo  endpoint actually returns the correct username.

1. Set up oauth2-proxy with a htaccess file with a single user in it
2. Set up login with an oauth2 provider
2. turn on --pass-basic-auth
3. Login as oauth2  user and and check header
4.  Login as htaccess user and check header

## Context

Broke all our robot users that use htaccess for authentication after upgrading to 7.x series. 

## Your Environment

OAUTH2_PROXY_REVERSE_PROXY: "true"
OAUTH2_PROXY_PROVIDER: google
OAUTH2_PROXY_SCOPE: email
OAUTH2_PROXY_EMAIL_DOMAINS: example.com
OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
OAUTH2_PROXY_HTTP_ADDRESS: ":4180"
OAUTH2_PROXY_HTPASSWD_FILE: /etc/secret/htaccess
OAUTH2_PROXY_SILENCE_PING_LOGGING: "true"
OAUTH2_PROXY_PASS_BASIC_AUTH: "true"
OAUTH2_PROXY_PREFER_EMAIL_TO_USER: "true"

- Version used:  
- 6.1.1  works
- 7.0.1  fails

### PR DESCRIPTION
**Pull request by JoelSpeed**
## Description

When we changed the way that headers were injected, we lost the ability for a basic auth session to respect the preferEmailToUser option. This should fix that by copying the user to the email field when the option is supplied

## Motivation and Context

Fixes #1079 

## How Has This Been Tested?

Unit tests

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

File: pkg/middleware/basic_session.go [hunk 1]
```diff
@@ -22,7 +22,19 @@ func NewBasicAuthSessionLoader(validator basic.Validator, sessionGroups []string
 // If no authorization header is found, or the header is invalid, no session
 // will be loaded and the request will be passed to the next handler.
 // If a session was loaded by a previous handler, it will not be replaced.
-func loadBasicAuthSession(validator basic.Validator, sessionGroups []string, next http.Handler) http.Handler {
+func loadBasicAuthSession(validator basic.Validator, sessionGroups []string, preferEmail bool, next http.Handler) http.Handler {
+	// This is a hack to be backwards compatible with the old PreferEmailToUser option.
```
Comment (NickMeves) [inline pkg/middleware/basic_session.go:26]: Maybe add a `TODO` in the comment so our IDEs can pester us over time so we remember to remove this?

**Review by NickMeves — APPROVED** [review]
LGTM

**Comment by JoelSpeed** [comment]
Added the TODO and updated the changelog, this is ready to merge IMO
