### PR TITLE
Ensure redirect URI always has a scheme

### LINKED ISSUE #1044: Google OAuth flow fails in 7.0.1 because redirect_uri doesn't have a scheme
Google does not allow an OAuth `redirect_uri` in the form of `//host/path`

## Expected Behavior

After click the "Sign in with Google" button I would expect to see a google sign-in page

## Current Behavior

Instead of a Google sign-in page I see a Google error screen with this text:

```
Authorization Error
Error 400: invalid_request
Invalid parameter value for redirect_uri: Missing scheme: //mysite.com/oauth2/callback
``` 

## Possible Solution

This was working as expected in version 6.1.1, but the behavior has changed in 7.0.1. I know that I can specify the redirect-url in the configuration as workaround (or stick with 6.1.1)

## Steps to Reproduce (for bugs)

1. Create a Google Oauth2 application
2. Start up a 7.0.1 proxy with these params: `--upstream=http://xxx:8000/ --http-address=0.0.0.0:4180 --cookie-secret xxx --email-domain=xxx.com --client-id=XXX.apps.googleusercontent.com --client-secret=XXX`
3. visit the proxy URL and click "Sign in with Google"

## Context

This is not blocking me right now, but seems like a regression.

## Your Environment

OSX Docker Host
Running this docker image: `quay.io/oauth2-proxy/oauth2-proxy@sha256:15eaf47e0ca8b15d668f5cb5da67f028abe251a2855a6b1c9344080c5735b59a`

Upstream is another docker app managed by docker-compose

- Version used: 7.0.1

### PR DESCRIPTION
**Pull request by JoelSpeed**
## Description

Ensure that the OAuth redirect URI always has a scheme associated with it

## Motivation and Context

Fixes #1044 and restores the behaviour to pre-v7

## How Has This Been Tested?

None yet, tests to be added

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.
- [ ] I have added appropriate tests

### CODE REVIEW

File: oauthproxy.go [hunk 1]
```diff
@@ -902,6 +903,11 @@ func (p *OAuthProxy) getOAuthRedirectURI(req *http.Request) string {
 	rd.Host = requestutil.GetRequestHost(req)
 	rd.Scheme = requestutil.GetRequestProto(req)
 
+	// If there's no scheme in the request, we should still include one
```
Comment (NickMeves) [inline oauthproxy.go:906]: Interesting -- good find. I blanked on the possibility that `Scheme` could be empty from http.Requests when trying to replace the previous logic that determined HTTPS vs HTTP purely if `CookieSecure` was true or false.

**Review by NickMeves — APPROVED** [review]

File: oauthproxy.go (hunk 1 above)
Comment (NickMeves) [reply oauthproxy.go:906]: @JoelSpeed I wonder... is this backwards compatibility we want to support -- or should we use this opportunity for forced security by default?

This authorization endpoint response will have the OAuth `authorization_code` for the token endpoint. That redirect REALLY should be HTTPS (and I actually think some OIDC providers will not allow this to be set to HTTP in their allowlist).

I wonder instead should we force this to be `https` if none of the other mechanisms (X-Forwarded-Proto/Scheme detection) made it `http` for some reason.

Then a user needs to consciously decide they want to be insecure and set it explicitly to `http://...` in the `redirect_uri` config flag?

**Review by NickMeves — CHANGES_REQUESTED** [review]
Rescinding my approval for a bit so we have the opportunity to discuss the security implications of this design.

File: oauthproxy.go (hunk 1 above)
Comment (NickMeves) [reply oauthproxy.go:906]: The accidentally insecure scenario I want to protect against: users that think they are using HTTPS - but have HTTP -> HTTPS redirect either in OAuth2-Proxy directly or a proxy in front of it.

BUT forgot to set `CookieSecure` for some reason -- leading to a scenario where the auto-OAuth `redirect_uri` is computed as `http` and the `authorization_code` in the querystring to the token redeem endpoint is over HTTP the first time before an auto-redirect to the HTTPS version.

Comment (JoelSpeed) [reply oauthproxy.go:906]: I think defaulting to https to make this more secure could make sense, would infer to users that we are expecting them to use it securely and perhaps prompt them to think about why.

Just wondering how many people that would break though 🤔  @hoffrocket @grimurd Since I know this bug is affecting you both, do you host your OAuth2 Proxy ultimately as HTTPS or HTTP?

Comment (NickMeves) [reply oauthproxy.go:906]: Do we potentially want a warning message on startup that trips during the validation stage?

If we don't see an explicit `--redirect-url`, `--https-address`, `--cookie-secure=true` or `--reverse-proxy` config that would make us confident in our settings: give a warning that we can't dynamically determine the redirect_url scheme accurately, so we are defaulting to `HTTPS` - if you want `HTTP`, set it explicitly in `--redirect-url`

Comment (hoffrocket) [reply oauthproxy.go:906]: I found this when I was trying to test locally with the proxy running on `http://localhost...`. The actual deployment is `HTTPS`. I understand the challenge here-- you don't want a surprising outcome for the automatic redirect creation that downgrades the security. But there are other controls against that danger to consider-- Google, at least, will fail if the redirect url does match what's in the app configuration.

I think a waterfall of `configured redirect url` -> `X-FORWARDED-PROTO` -> `oauth2proxy is TLS` -> `http` could make sense.

File: pkg/validation/options.go [hunk 2]
```diff
@@ -175,6 +177,9 @@ func Validate(o *options.Options) error {
 	var redirectURL *url.URL
 	redirectURL, msgs = parseURL(o.RawRedirectURL, "redirect", msgs)
 	o.SetRedirectURL(redirectURL)
+	if o.RawRedirectURL == "" && !o.Cookie.Secure && !o.ReverseProxy {
```
Comment (NickMeves) [inline pkg/validation/options.go:180]: Nice!

**Review by NickMeves — APPROVED** [review]
LGTM!
