### PR TITLE
Close client connections after each redis test

### LINKED ISSUE #653: Miniredis session tests appear to leak file descriptors
Now that we've added redis cluster tests in addition to standard and sentinel, we appear to have too many miniredis's trying to get going.  Without upping my `ulimit` past the default OSX setting of 256, I fail about 168 tests in of the 243 specs:

```
              Unexpected error:
                  <*net.OpError | 0xc000c90f00>: {
                      Op: "read",
                      Net: "tcp",
                      Source: {IP: [127, 0, 0, 1], Port: 65173, Zone: ""},
                      Addr: {IP: [127, 0, 0, 1], Port: 64908, Zone: ""},
                      Err: {},
                  }
                  read tcp 127.0.0.1:65173->127.0.0.1:64908: i/o timeout
              occurred
```

I even tried to reuse miniredis instances and ran `FlushAll` between specs, but then I eventually still got `socket: too many open files occurred` attempting to talk to the miniredis server.

## Expected Behavior

The tests work locally with sensible default system settings on most developers systems so they don't get tripped up by tests failing on the redis sessions.

## Current Behavior

Tests fail unless I run `ulimit -n 1024` to up my system resources limit.

## Possible Solution

I tried to reuse the same miniredis between all specs and flushed the redis data in between tests, but that didn't seem to fix the issue easily.  Still had issues with resources on the socket connections eventually at the same point.  So I'm out of quick and easy ideas.

I also tried to limit the max file descriptors with a buffered channel.  I couldn't get that to work well either.  I don't know how we get around systems being slow to release open file descriptors after a `miniredis.Close()` since they are likely sitting in a `TIME_WAIT` state or whatever it is for a bit of time afterwards.

## Steps to Reproduce (for bugs)

1.) ulimit -n 256
2.) go test ./...

### PR DESCRIPTION
**Pull request by JoelSpeed**
## Description

Make sure we close connections in the redis client after each test

## Motivation and Context

Fixes #653 

## How Has This Been Tested?

`docker run --rm -it -v $PWD:/go/src/github.com/oauth2-proxy/oauth2-proxy --workdir /go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/sessions/redis golang:1.14 bash -c "ulimit -n 256 && ulimit -a && go test -v ./..."`

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

File: pkg/sessions/redis/client.go [hunk 1]
```diff
@@ -12,6 +12,10 @@ type Client interface {
 	Get(ctx context.Context, key string) ([]byte, error)
 	Set(ctx context.Context, key string, value []byte, expiration time.Duration) error
 	Del(ctx context.Context, key string) error
+
+	// close is only used in tests to ensure that client connections are terminated
+	// after each test is finished
+	close() error
```
Comment (NickMeves) [inline pkg/sessions/redis/client.go:18]: Any advantage to just doing these in the tests themselves directly rather than adding to the interface and implementation just for tests sake?

`redisStore.Client.(*client).Close()`

And for cluster:

`redisStore.Client.(*clusterClient).Close()`

Comment (JoelSpeed) [reply pkg/sessions/redis/client.go:18]: I'm happy either way to be honest, it's not uncommon for things like this to be implemented for the tests sake within Go I don't think, but I could just do as you've suggested.

I deliberately set the method to private because it's only for testing so it's not on the public interface

Comment (JoelSpeed) [reply pkg/sessions/redis/client.go]: I just had another look and decided I will change it, added a small `closer` interface that can be used in the test, WDYT?

Comment (NickMeves) [reply pkg/sessions/redis/client.go]: Nice -- this looks super clean. I like it.

File: pkg/sessions/redis/session_store_test.go [hunk 2]
```diff
@@ -41,12 +48,25 @@ var _ = Describe("Redis SessionStore Tests", func() {
 		mr.Close()
 	})
 
+	JustAfterEach(func() {
+		// Release any connections immediately after the test ends
+		if redisStore, ok := ss.(*SessionStore); ok {
+			if redisStore.Client != nil {
+				redisStore.Client.(closer).Close()
```
Comment (NickMeves) [inline pkg/sessions/redis/session_store_test.go:55]: Since `Close()` can error - I think we should assert that it didn't error.

Otherwise someday some developer will run into the same unclear socket timeout/file descriptor errors that are less clear.

Comment (JoelSpeed) [reply pkg/sessions/redis/session_store_test.go:55]: Good catch, gimme a second
