### PR TITLE
extract email from id_token for azure provider

### LINKED ISSUE #913: when protected resource other than Graph api is specified in azure provider the access token will be invalid to query Graph
## Expected Behavior
it should not use the access token destined to the protected resource to query Graph api

## Current Behavior
In azure provider, when protected resource `--resource` is specified to any resource other than Graph api, the access token will not be valid to query graph api for user's email. It results in 401 error: `{"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."}}}` in [GetEmailAddress](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/azure.go#L247)

## Possible Solution
There is actually no need to query Graph api for user email. Either the id_token or access_token can be configured to emit such claim. As such, we should check the token's claim first. I believe oidc provider is already doing that.

## Steps to Reproduce (for bugs)

repro script: https://github.com/weinong/brownbag-oauth-oidc/blob/master/01_authorization-code.sh
just change the resource in L21 to a different one.

## Context
This impacts any use of protected resource in Azure AD such as
https://github.com/kubeapps/kubeapps/issues/2118

## Your Environment
Azure AD

- Version used:
5.0.0, but it is the same logic in any other versions.

### PR DESCRIPTION
**Pull request by weinong**
extract email from id_token, if present, for azure provider

## Description
this change fixes a bug when `--resource` is specified with non-Graph api and the access token destined to --resource is used to call Graph api

## Motivation and Context
Fixes #913

## How Has This Been Tested?
unit test and end to end validation

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

File: providers/azure.go [hunk 1]
```diff
@@ -235,11 +238,35 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
 	return email, err
 }
 
+func getEmailFromIDToken(idToken string) (string, error) {
+	jwt := strings.Split(idToken, ".")
+	jwtData := strings.TrimSuffix(jwt[1], "=")
+	b, err := base64.RawURLEncoding.DecodeString(jwtData)
+	if err != nil {
+		return "", fmt.Errorf("jwt is mailformed: %w", err)
```
Comment (latiif) [inline providers/azure.go:246]: Typo in "malformed".

Comment (lindhe) [reply providers/azure.go:246]: A mailformed jwt should be fine in `getEmailFromIDToken`, right? ;)

Comment (latiif) [reply providers/azure.go:246]: I thought of this, but then if `jwt` is _mailformed_ why does is it appear in an error message inside `getEmailFromIDToken` :man_shrugging:

Comment (weinong) [reply providers/azure.go]: good eyes!

File: providers/azure.go [hunk 2]
```diff
@@ -233,11 +236,35 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
...
+}
+
 // GetEmailAddress returns the Account email address
 func (p *AzureProvider) GetEmailAddress(ctx context.Context, s *sessions.SessionState) (string, error) {
 	var email string
-	var err error
 
+	if s.IDToken != "" {
+		return getEmailFromIDToken(s.IDToken)
+	}
```
Comment (JoelSpeed) [inline providers/azure.go:267]: It would be better to first try the ID Token extraction, and then try the profile URL if the ID Token does not include an email.

Out of interest, comparing this with the OIDC provider, I noticed that the Azure provider doesn't extract User/Email/Groups during the Redeem process, but the OIDC provider does. Might be better to try and bring the functionality inline with the OIDC provider and try to extract claims from the ID Token during redeem, and then leave `GetEmailAddress` as a fallback in case the ID Token doesn't include the email

Comment (NickMeves) [reply providers/azure.go:267]: FYI - `GetEmailAddress` should be considered deprecated in favor of `EnrichSessionState`.

`EnrichSessionState` is called immediately after `redeem` logic in `OAuthCallback`. It is now the place to do any getters & setters on the session.

Historically, a lot of people hacked a lot of unrelated functionality into `GetuserName` & `GetEmailAddress` because those were the only post `redeem` hooks to hit things like the ProfileURL. Now `EnrichSessionState` and `Authorize` are the appropriate methods for various post redeem logic.

Comment (NickMeves) [reply providers/azure.go:267]: For more context: https://github.com/oauth2-proxy/oauth2-proxy/issues/883

Comment (weinong) [reply providers/azure.go:267]: @NickMeves doesn't [enrichSessionState()](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L410) call `GetEmailAddress()` first. Do you suggest remove `GetEmailAddress()` from Azure provider?

Comment (NickMeves) [reply providers/azure.go:267]: The intention is all previous uses of `GetUserName` and `GetEmailAddress` (where the original intent was they were just getters, but a bazillion providers made those methods mutate the session) make the switch to `EnrichSessionState`.

I've refactored all users of `GetUserName` already so it has been removed. Trying to hit `GetEmailAddress` as people touch it in PRs.

You probably just need to rename the method and tweak the logic a little bit to get the returned email into the `session.Email`.

Comment (weinong) [reply providers/azure.go]: @NickMeves i've made the refactoring, PTAL
@JoelSpeed I made the change to extract email from id token as best effort. Regarding the feedback to move email extraction into `Redeem()` logic, I think it's still arguable as I see different providers all implement it differently. For my naive understanding, `Redeem` should just redeem for the token. How to interpret and process these tokens seems to be EnrichSessionState's business?

Comment (NickMeves) [reply providers/azure.go]: I think any code-ful extraction of an IDToken claim could be in Redeem or EnrichSessionState, both work. I think you'll see most other providers handle this in Redeem if they have it available to them. But that might be a legacy byproduct since `GetUserName` and `GetEmailAddress` were very tailored to a network call to retrieve these details from a profile URL or something.

If there's any network traffic, that 100% belongs in `EnrichSessionState`

Comment (NickMeves) [reply providers/azure.go]: Added context: https://github.com/oauth2-proxy/oauth2-proxy/issues/883

**Comment by weinong** [comment]
this will address #779 as well

File: providers/azure.go (hunk 2 above)
Comment (weinong) [reply providers/azure.go]: @NickMeves can we refactor that in a separate PR? :)

Comment (NickMeves) [reply providers/azure.go]: Doing a quick eye test, you seem fine doing all the logic in `EnrichSessionState` - I don't see what you need to refactor

Comment (weinong) [reply providers/azure.go]: let me know what else I need to do. thanks!

Comment (NickMeves) [reply providers/azure.go]: > It would be better to first try the ID Token extraction, and then try the profile URL if the ID Token does not include an email.
> 
> Out of interest, comparing this with the OIDC provider, I noticed that the Azure provider doesn't extract User/Email/Groups during the Redeem process, but the OIDC provider does. Might be better to try and bring the functionality inline with the OIDC provider and try to extract claims from the ID Token during redeem, and then leave `GetEmailAddress` as a fallback in case the ID Token doesn't include the email

So upon closer look at the PR, I would actually strongly agree with @JoelSpeed's point -- we should really aim to consolidate the logic for claim extration from an IDToken that works across providers.  Here's the logic from OIDC: https://github.com/oauth2-proxy/oauth2-proxy/blob/8bed7aafbdb2cb6241b9655e983dd54d54b50531/providers/oidc.go#L229

(Ignore the requests to the profileURL as a fallback, I intend to move that to `EnrichSessionState` in OIDC: https://github.com/oauth2-proxy/oauth2-proxy/issues/883).

Big reason we should consolidate: A frequent feature request we intend to implement soon is arbitrary claim -> header mappings, so users have full control of passing claims to their backend apps in `X-Forwarded-*` headers. If any provider that has IDTokens with claims uses a common function, adding that functionality will apply to much more providers than just OIDC.

Comment (NickMeves) [reply providers/azure.go]: Also, what support does Azure provide for OIDC discovery documents (`openid-configuration` & `jwks_uri`) that an `oidc.IDTokenVerifier` would use?

The reason I ask is if Azure is mostly OIDC ready, we can also make it support Bearer auth. I have this refactor in flight as well that aims to make any provider that supports OIDC Verifiers be able to be used with bearer token auth:
https://github.com/oauth2-proxy/oauth2-proxy/pull/869#discussion_r527412285

File: providers/azure.go [hunk 3]
```diff
@@ -233,13 +236,44 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
 	return email, err
 }
 
-// GetEmailAddress returns the Account email address
-func (p *AzureProvider) GetEmailAddress(ctx context.Context, s *sessions.SessionState) (string, error) {
+func getEmailFromIDToken(idToken string) (string, error) {
+	jwt := strings.Split(idToken, ".")
+	jwtData := strings.TrimSuffix(jwt[1], "=")
+	b, err := base64.RawURLEncoding.DecodeString(jwtData)
```
Comment (NickMeves) [inline providers/azure.go:242]: See my note below on consolidating logic & common `*oidc.IDTokenVerifiers`.

BUT, if those aren't applicable, I'm not a fan of this logic. Manually tearing apart a JWT like this geels hacky.

Even if its a dummy `oidc.IDTokenVerifier` like in the unit tests, this would be much cleaner if we convert the tokens string to an actual `oidc.IDToken`. Here is a sample using an `oidc.IDTokenVerifier` where the `oidc.KeySet` we use just has a dummy implementation of the `VerifySignature` method:

https://github.com/oauth2-proxy/oauth2-proxy/blob/8bed7aafbdb2cb6241b9655e983dd54d54b50531/pkg/middleware/jwt_session_test.go#L81

Comment (NickMeves) [reply providers/azure.go:242]: Or some better way to convert a `string` -> `oidc.IDToken` -- but I'm not sure there's a cleaner way, hence we have the mock KeySets in our tests to help create `oidc.IDTokens`

File: providers/azure.go (hunk 2 above)
Comment (weinong) [reply providers/azure.go]: I will work on moving the email extraction to `Redeem`

> Also, since I see the Azure provider gives back an ID Token, what support does Azure provide for OIDC discovery documents (openid-configuration & jwks_uri) that an oidc.IDTokenVerifier would use?

when you specify the AAD issuer, oidc library will be able to retrieve the oidc discovery document.
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#fetch-the-openid-connect-metadata-document

Comment (weinong) [reply providers/azure.go]: To be clear, it is Okay for `Redeem` to make network call to download jwks to verify the id_token, right?

Comment (weinong) [reply providers/azure.go]: > To be clear, it is Okay for `Redeem` to make additional network call to download jwks to verify the id_token, and it is expected for each provider to implement it, right?

FWIW, I only see oidc and gitlab providers doing token verification in `Redeem`. Let me know what is the desired pattern going forward.

Comment (NickMeves) [reply providers/azure.go]: Do it in `EnrichSessionState`.

And it is uniform, refactor the claim extraction logic to a helper method in `util.go` that this provider & OIDC consume. This way future improvements to it will be available in Azure for you and not just OIDC.

If that isn't an easy refactor, there's also this sample of a cleaner way to get JWT claims than the current logic: https://github.com/oauth2-proxy/oauth2-proxy/blob/8bed7aafbdb2cb6241b9655e983dd54d54b50531/providers/logingov.go#L104

File: providers/azure.go (hunk 3 above)
Comment (weinong) [reply providers/azure.go]: i refactored to use `jwt` package to extract claims

File: providers/azure.go (hunk 2 above)
Comment (weinong) [reply providers/azure.go]: i left the token claim extraction in `EnrichSessionState` and did a small refactoring to use `jwt` package to extract claims. Hope it would suffice.

File: providers/azure.go [hunk 4]
```diff
@@ -233,13 +234,50 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
 	return email, err
 }
 
-// GetEmailAddress returns the Account email address
-func (p *AzureProvider) GetEmailAddress(ctx context.Context, s *sessions.SessionState) (string, error) {
+// full claims that can be emitted by AAD are
+// https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens
```
Comment (NickMeves) [inline providers/azure.go:238]: Thanks for the documentation link, this will help in the future 👍

File: providers/azure.go [hunk 5]
```diff
@@ -233,13 +234,50 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
...
+}
+
+// EnrichSessionState finds the email to enrich the session state
+func (p *AzureProvider) EnrichSessionState(ctx context.Context, s *sessions.SessionState) error {
 	var email string
-	var err error
+
+	if s.IDToken != "" {
+		email, err := getEmailFromIDToken(s.IDToken)
+		if err != nil || email == "" {
```
Comment (NickMeves) [inline providers/azure.go:271]: if `email == ""` is a thing and we don't like it, I feel like it should be handled in `getEmailFromIDToken` and raise an appropriate error there.

Then this can be simplified and clearer to something like this:
```
	if s.IDToken != "" {
		email, err := getEmailFromIDToken(s.IDToken)
		if err == nil {
			s.Email = email
			return nil
		}
		logger.Errorf("unable to find email from id_token: %s", err)
	}
```

File: providers/azure.go [hunk 6]
```diff
@@ -233,13 +234,50 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
...
+		return "", err
+	}
+	if claims.Email == "" {
+		return "", errors.New("missing email claim from id_token")
+	}
+	return claims.Email, nil
+}
+
+// EnrichSessionState finds the email to enrich the session state
+func (p *AzureProvider) EnrichSessionState(ctx context.Context, s *sessions.SessionState) error {
```
Comment (NickMeves) [inline providers/azure.go:266]: With your new logic, the return count & conditional branching count in this function is getting quite high. I expect CodeClimate complained and said this needs refactoring?

For instance the profileURL call for JSON & conditional logic for extracting an email from the response is likely best in another private method adjacent to your new `getEmailFromIDToken` implementation.

File: providers/azure_test.go [hunk 7]
```diff
@@ -122,82 +122,134 @@ func testAzureBackend(payload string) *httptest.Server {
...
 
 	session := CreateAuthorizedSession()
-	email, err := p.GetEmailAddress(context.Background(), session)
+	err := p.EnrichSessionState(context.Background(), session)
 	assert.Equal(t, "type assertion to string failed", err.Error())
-	assert.Equal(t, "", email)
+	assert.Equal(t, "", session.Email)
+}
+
+func TestAzureProviderEnrichSessionStateFromIDToken(t *testing.T) {
```
Comment (NickMeves) [inline providers/azure_test.go:203]: Can you refactor these to use test tables? While this style tests are still in the code base, in general we don't allow new merges using it so we can ween ourselves off of this style for better, cleaner tests in the long term.

Test tables are OK. Ginkgo is our preferred testing format, but I don't think the refactor to bring Ginkgo test suit support to the `providers` package has merged yet.

File: providers/azure_test.go [hunk 8]
```diff
@@ -122,82 +122,134 @@ func testAzureBackend(payload string) *httptest.Server {
...
+	p := testAzureProvider("")
+
+	session := CreateAuthorizedSession()
+	session.IDToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiZW1haWwiOiJmb29AYmFyLmNvbSIsImlhdCI6MTUxNjIzOTAyMn0.XRuL4Y2VPSToNB8vMvmlB-X3BwahUJzUXNx6vmzODjk"
```
Comment (NickMeves) [inline providers/azure_test.go:207]: Can you add comments that nicely display the inner decoded JWT payload you are using in these tests so they are easier for the next contributors to eyeball and understand what is being tested?

File: providers/azure.go (hunk 6 above)
Comment (NickMeves) [reply providers/azure.go:266]: Are you able to get this to an `oidc.IDToken` via an `oidc.Verifier` ([sample](https://github.com/oauth2-proxy/oauth2-proxy/blob/3ff0c23a9e418875cdd7460b0a6a5b40dea71770/providers/oidc_test.go#L151)) and use the `Claims` method like here: https://github.com/oauth2-proxy/oauth2-proxy/blob/3ff0c23a9e418875cdd7460b0a6a5b40dea71770/providers/oidc.go#L233

I figure I'll eventually be on the hook for generic claim -> header support across all providers. When that happens, I'll need to consolidate logic. This would be the 3rd different way to extract IDToken claims, so I'd like to consolidate, at least onto the same `oidc` library if we aren't refactoring the logic into a dedicated method in `utils` at this point.

File: providers/azure.go [hunk 9]
```diff
@@ -233,13 +234,50 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
...
+func (aadIDTokenClaims) Valid() error {
+	return nil
+}
+
+func getEmailFromIDToken(idToken string) (string, error) {
+	claims := &aadIDTokenClaims{}
+	parser := jwt.Parser{}
+
+	// ParseUnverified to extract claims without verifying signature
+	if _, _, err := parser.ParseUnverified(idToken, claims); err != nil {
```
Comment (NickMeves) [inline providers/azure.go:256]: Are you able to get this to an `oidc.IDToken` via an `oidc.Verifier` ([sample](https://github.com/oauth2-proxy/oauth2-proxy/blob/3ff0c23a9e418875cdd7460b0a6a5b40dea71770/providers/oidc_test.go#L151)) and use the `Claims` method like here: https://github.com/oauth2-proxy/oauth2-proxy/blob/3ff0c23a9e418875cdd7460b0a6a5b40dea71770/providers/oidc.go#L233

I figure I'll eventually be on the hook for generic claim -> header support across all providers. When that happens, I'll need to consolidate logic. This would be the 3rd different way to extract IDToken claims, so I'd like to consolidate, at least onto the same `oidc` library if we aren't refactoring the logic into a dedicated method in `utils` at this point.

**Review by NickMeves — CHANGES_REQUESTED** [review]
I think this is a good enhancement to support, but the implementation is deviating from the direction we are trying to refactor and standardize the codebase on in couple of places.

I left some notes to help give context behind the recommendation and my thinking.

File: providers/azure.go (hunk 6 above)
Comment (NickMeves) [reply providers/azure.go:266]: Ah, yep 😉  https://codeclimate.com/github/oauth2-proxy/oauth2-proxy/pull/914

File: providers/azure_test.go (hunk 7 above)
Comment (NickMeves) [reply providers/azure_test.go:203]: Here's the PR that includes the Ginkgo addition and some sample tests: https://github.com/oauth2-proxy/oauth2-proxy/pull/630/files#diff-233c3f5da886b2facdebcec5f9802b1df67ef0252d55be63a882a6eb49661d85R227

This PR is almost at the finish line if you want to build off its work with Ginkgo tests.

File: providers/azure.go (hunk 9 above)
Comment (weinong) [reply providers/azure.go:256]: both `oidc` and `jwt` libraries are doing token validations, and I'm with you, totally agree that these need to be consolidated. However, what's not clear to me is the responsibility of each provider, and when this validation should be consolidated into. The code I refactored here is the one without any dependency such as jwks.
how do you think? perhaps leave the consolidation out of this PR?

Comment (NickMeves) [reply providers/azure.go:256]: I'm leaning on you a little bit since you have a good understanding of Azure & the OIDC specifics of it 😄 

When I take on a lot of these refactors in the future for new features, Azure isn't a provider I use myself. So I won't have a test account or know the nuances of it.

That's why I'm looking to get the guts of what we need to consolidate on as close as possible & have strong test cases that emulate Azure IDTokens well so in a future refactor I can spruce up code and rely on existing tests passing to be confident in an changes to the Azure provider.

Comment (NickMeves) [reply providers/azure.go:256]: At the very least, just use the `oidc.Verifier` I think -- you would need the same guts as the struct & `Valid` method you made for the `jwt` library right?

At least that way, the foundation is in place with the right `issuer` & `audience` values in code.

File: providers/azure.go (hunk 6 above)
Comment (weinong) [reply providers/azure.go:291]: i did some refactoring, it should be addressed now.

File: providers/azure_test.go (hunk 7 above)
Comment (weinong) [reply providers/azure_test.go]: done

File: providers/azure_test.go (hunk 8 above)
Comment (weinong) [reply providers/azure_test.go]: sure

File: providers/azure.go (hunk 5 above)
Comment (weinong) [reply providers/azure.go]: good suggestion. thanks!

File: providers/azure.go (hunk 9 above)
Comment (NickMeves) [reply providers/azure.go:264]: @JoelSpeed -- @weinong and I discussed offline: I don't think we should take any data from unverified tokens to be used in our auth critical `Email` or `Groups` session fields.

@weinong will wait until we wrap up this PR: https://github.com/oauth2-proxy/oauth2-proxy/pull/869

With that in place, if an Azure user wants this, they can setup the OIDC config options that would results in an `oidc.IDTokenVerifier` on the ProviderData struct. (as an added benefit this makes Azure bearer token authentication ready where it wasn't before).

If that is non-nil, this logic can proceed and extract claims from the IDToken to get an email (i.e. a user has setup the proper configs for Azure to say OIDC IDToken extraction is a safe route for identity extraction). Otherwise it will skip it and rely on the previous `ProfileURL` based methods to get an Email.

File: providers/azure_test.go [hunk 10]
```diff
@@ -122,82 +123,96 @@ func testAzureBackend(payload string) *httptest.Server {
...
+		{
+			Description:             "EnrichSessionState should return error when otherMails from Azure backend is not a valid type",
+			PayloadFromAzureBackend: `{ "mail": null, "otherMails": "", "userPrincipalName": null }`,
+			ExpectedEmail:           "",
+			ExpectedError:           errors.New("type assertion to string failed"),
+		},
+		{
+			Description: "EnrichSessionState should return email from id_token",
+			// { "sub": "1234567890", "email": "foo@bar.com", "iat": 1516239022 }
+			IDToken:       "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiZW1haWwiOiJmb29AYmFyLmNvbSIsImlhdCI6MTUxNjIzOTAyMn0.XRuL4Y2VPSToNB8vMvmlB-X3BwahUJzUXNx6vmzODjk",
```
Comment (NickMeves) [inline providers/azure_test.go:173]: Before I forget before we pause this work for a bit:

For these test cases can we get mock IDTokens that look like what Azure would give back (headers + payloads, sig can be garbage).

That will make testing compatibility with Azure OIDC changes a lot easier for other contributors

Comment (weinong) [reply providers/azure_test.go:173]: I believe we will need to properly "generate and sign" these token claims once oidc is implemented in the provider.

Comment (NickMeves) [reply providers/azure_test.go:173]: You don't have to expose a real token & signature of yours.  You can rip up the insides and replace the payload claims object with mock values and re-encode.

We'd do a setup like this in unit tests where we don't actually verify the signature, we just use a mock JWKS: https://github.com/oauth2-proxy/oauth2-proxy/blob/3ff0c23a9e418875cdd7460b0a6a5b40dea71770/providers/oidc_test.go#L110

File: providers/azure.go [hunk 11]
```diff
@@ -230,44 +231,84 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
...
+}
 
-	email, err = json.Get("userPrincipalName").String()
-	if err != nil {
-		logger.Errorf("failed making request %s", err)
-		return "", err
+// EnrichSessionState finds the email to enrich the session state
+func (p *AzureProvider) EnrichSessionState(ctx context.Context, s *sessions.SessionState) error {
+	var email string
+	var err error
```
Comment (JoelSpeed) [inline providers/azure.go:293]: These don't need declaring here, please declare them inline with the `:=` syntax instead

File: providers/azure.go [hunk 12]
```diff
@@ -230,44 +231,84 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
...
+
+	if s.IDToken != "" {
+		email, err := getEmailFromIDToken(s.IDToken)
+		if err == nil {
+			s.Email = email
+			return nil
+		}
+		logger.Errorf("unable to find email from id_token: %s", err)
```
Comment (JoelSpeed) [inline providers/azure.go:301]: It's idiomatic to use `%v` in a format string for error types in Go, please switch this and other logger calls to use `%v", err` at the end
```suggestion
		logger.Errorf("unable to find email from id_token: %v", err)
```

**Comment by NickMeves** [comment]
@weinong PR covering the concept we discussed: Make OIDC functionality available to all providers: https://github.com/oauth2-proxy/oauth2-proxy/pull/936

**Comment by weinong** [comment]
@NickMeves @JoelSpeed I updated the PR to enable oidc provider and to extract email from id_token in Redeem after id_token verification

**Comment by NickMeves** [comment]
@weinong - Lets pause this work until I wrap up this PR: https://github.com/oauth2-proxy/oauth2-proxy/pull/936

You will want to use these new global OIDC helpers: https://github.com/oauth2-proxy/oauth2-proxy/pull/936/files#diff-b4ef38e96ab5394c070aff6c070843820d904f7f06b36a81bd52384edd5214caR114

Particularly `buildSessionFromClaims`.  This way you will have Azure be future proof and support the future adhoc claim -> session -> headers logic that is coming soon.

**Comment by lindhe** [comment]
I guess this can be unpaused now, since #936  is merged?

**Comment by NickMeves** [comment]
> I guess this can be unpaused now, since #936 is merged?

Yup. So ideally I want to migrate the Azure provider to be completely OIDC based (using mostly methods from OIDCProvider) to consolidate code) and we'd move away from this legacy implementation long term.

New one would be called something like `azure-oidc` and in v8 we'd deprecate this existing `azure` provider and move the OIDCProvider based version to take over the `azure` provider name.

I'll link other issues in other providers with more details that will also ideally get this refactor.

**Comment by weinong** [comment]
@NickMeves you mean I can still continue this PR, right?

**Comment by NickMeves** [comment]
> @NickMeves you mean I can still continue this PR, right?

Yup -- If you don't mind can you also peek at this issue and see if this same refactor makes sense now or sometime later for Azure as well (to embrace the OIDC protocol and reduce duplicate OIDC flow logic that the OIDC Provider implements)?

If you keep your improvement in the existing provider and don't switch to an Azure provider that has `OIDCProvider` as a baseline, be sure to use the global OIDC helper methods we currently expose on the base `ProviderData` struct. Hopefully we have all the helper methods you need to manage OIDC logic.

**Comment by weinong** [comment]
@NickMeves I refactored to use the oidc verifier, if configured, to verify id_token. I intend not to use the built-in function to verify id_token and to build the session state as the id_token from Azure AD v1 endpoint (the default) isn't very oidc compliant.

File: providers/azure.go [hunk 13]
```diff
@@ -107,17 +107,16 @@ func overrideTenantURL(current, defaultURL *url.URL, tenant, path string) {
 	}
 }
 
-// Redeem exchanges the OAuth2 authentication token for an ID token
-func (p *AzureProvider) Redeem(ctx context.Context, redirectURL, code string) (*sessions.SessionState, error) {
+func (p *AzureProvider) prepareRedeem(redirectURL, code string) (url.Values, error) {
+	params := url.Values{}
```
[the remark this answers is not in the document]
Comment (weinong) [reply providers/azure.go:111]: this refactor is to deal with the static analysis complaining `Redeem()` function had too many returns :)

**Comment by weinong** [comment]
@JoelSpeed @NickMeves can you help take a look please?

**Comment by NickMeves** [comment]
@weinong Sorry for the delay, I'll give this a look this weekend.

FYI, since v7.0.0 just released we're holding on merging anything major for a week or two so we can get any emergency bugfixes needed in place and release v7.0.1.

File: providers/azure.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (JoelSpeed) [reply providers/azure.go:111]: Ahh that makes sense, I still think we could move this particular declaration later in this new function though, wdyt?

File: providers/azure.go [hunk 14]
```diff
@@ -230,44 +276,48 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
 		err = otherMailsErr
 	}
 
+	if err != nil || email == "" {
+		email, err = json.Get("userPrincipalName").String()
+		if err != nil {
+			logger.Errorf("unable to find userPrincipalName: %s", err)
+			return "", err
+		}
+	}
```
Comment (JoelSpeed) [inline providers/azure.go:285]: Long term, this feels a bit weird. I would have thought as an admin you would want to be deterministic about where the email comes from rather than having it try 3 different possible fields

File: providers/azure.go [hunk 15]
```diff
@@ -126,6 +125,15 @@ func (p *AzureProvider) Redeem(ctx context.Context, redirectURL, code string) (*
 	if p.ProtectedResource != nil && p.ProtectedResource.String() != "" {
```
Comment (NickMeves) [inline providers/azure.go:125]: Making a note of this here as well -- In the very related ADFS Provider PR, I was curious how feasible it was to use the default OIDC Provider or `oauth2.Config` for token redemption stuff. At least for ADFS, there's an opportunity to add this non-standard parameter into the `scope` parameter, is that a thing for Azure too?

https://github.com/oauth2-proxy/oauth2-proxy/pull/1021#discussion_r571505330

File: providers/azure.go [hunk 16]
```diff
@@ -126,6 +125,15 @@ func (p *AzureProvider) Redeem(ctx context.Context, redirectURL, code string) (*
...
 		params.Add("resource", p.ProtectedResource.String())
 	}
+	return params, nil
+}
+
+// Redeem exchanges the OAuth2 authentication token for an ID token
+func (p *AzureProvider) Redeem(ctx context.Context, redirectURL, code string) (*sessions.SessionState, error) {
+	params, err := p.prepareRedeem(redirectURL, code)
```
Comment (NickMeves) [inline providers/azure.go:133]: If we did this: https://github.com/oauth2-proxy/oauth2-proxy/pull/1021#discussion_r571505330

Could we move Redeem to use the `oauth2.Config` like this: https://github.com/oauth2-proxy/oauth2-proxy/blob/d2ffef2c7e0a622295c42cb2fdd70ef14593d03c/providers/oidc.go#L36

And not need to manually make our own `token_endpoint` call from scratch in the helper method?

File: providers/azure.go [hunk 17]
```diff
@@ -230,44 +276,48 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
...
-	}
+	return getEmailFromJSON(json)
+}
 
-	email, err = json.Get("userPrincipalName").String()
-	if err != nil {
-		logger.Errorf("failed making request %s", err)
-		return "", err
+// EnrichSessionState finds the email to enrich the session state
+func (p *AzureProvider) EnrichSessionState(ctx context.Context, s *sessions.SessionState) error {
```
Comment (NickMeves) [inline providers/azure.go:308]: The interface method is named `EnrichSession` now -- I promise I won't refactor it anymore 😅 

Can we move this up to the top? I find it helpful for people consuming providers to have the methods in the same order that the `OAuthProxy` will call them in for the login flow: (GetLoginURL, Redeem, EnrichSession). I'm trying to shift to that organization as I refactor more providers

File: providers/azure.go [hunk 18]
```diff
@@ -230,44 +276,48 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
...
+	if s.Email != "" {
+		return nil
 	}
 
+	email, err := getEmailFromProfileAPI(ctx, s.AccessToken, p.ProfileURL.String())
 	if email == "" {
-		logger.Errorf("failed to get email address")
-		return "", err
+		logger.Errorf("failed to get email address: %s", err)
```
Comment (NickMeves) [inline providers/azure.go:315]: This feels like a bug (that looks like it might've been there before): the `email == ""` check is after the `err != nil` check, but in the `email == ""` check we return `err` (which is `nil`).

I think we want to make our own custom `errors.New("...")` here if the email is blank right? Do we want to explicitly call the `logger.Errorf` here, or make a proper error with the details and let the logging get handled when the error is logged?

File: providers/azure.go (hunk 14 above)
Comment (NickMeves) [reply providers/azure.go:285]: Agreed - but this looks to be the existing functionality?

I'm more curious after seeing the ADFS PR #1021 where that contributor wanted to use the `upn` claim as the `session.User` how people want to consume that field in general?

Is an alternative to the traditional `session.User = claim.Subject` something that is in demand? 🤔

File: providers/azure.go [hunk 19]
```diff
@@ -149,13 +157,40 @@ func (p *AzureProvider) Redeem(ctx context.Context, redirectURL, code string) (*
...
+
+	return session, nil
+}
+
+func (p *AzureProvider) verifyIDTokenAndExtractEmail(ctx context.Context, rawIDToken string) (string, error) {
+	idToken, err := p.Verifier.Verify(ctx, rawIDToken)
+	if err != nil {
+		return "", err
+	}
+	var idTokenClaims struct {
```
Comment (NickMeves) [inline providers/azure.go:186]: `ProviderData` has `getClaims` available if that helps here

File: providers/azure.go [hunk 20]
```diff
@@ -149,13 +157,40 @@ func (p *AzureProvider) Redeem(ctx context.Context, redirectURL, code string) (*
...
+		Email string `json:"email,omitempty"`
+	}
+	if err := idToken.Claims(&idTokenClaims); err != nil {
+		return "", err
+	}
+
+	return idTokenClaims.Email, nil
```
Comment (NickMeves) [inline providers/azure.go:193]: Is the `email_verified` claim a thing in Azure? If so, I think we need to respect that claim & related options we have in oauth2-proxy around trusting emails if they aren't verified.  Here's a sample: https://github.com/oauth2-proxy/oauth2-proxy/blob/d2ffef2c7e0a622295c42cb2fdd70ef14593d03c/providers/provider_data.go#L163

Comment (weinong) [reply providers/azure.go:193]: it's not. https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims

File: providers/azure.go (hunk 14 above)
Comment (weinong) [reply providers/azure.go:285]: AAD has two versions and each has its own set of optional claims. Even id_token is optional. :) So it's highly configurable. In general, for v1 format, `upn` makes sense. I don't know the history of adopting `userPrincipalName`, though. But I think we should at least keep it as compatible as it is?

Comment (weinong) [reply providers/azure.go:285]: `session.User = claim.Subject` would be a bad idea on Azure AD as it's a pairwise identifier - it is unique to a particular application ID.
https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#payload-claims

Comment (NickMeves) [reply providers/azure.go:285]: Agreed - for your PR, lets keep this existing logic backwards compatible and we can revisit it later in a breaking release if we want 👍

File: providers/azure.go (hunk 16 above)
Comment (NickMeves) [reply providers/azure.go:133]: This is me just thinking out loud -- ignore this for this PR; I think the Azure `resource` parameter needs more thorough investigation outside of this PR.

File: providers/azure.go (hunk 17 above)
Comment (weinong) [reply providers/azure.go:308]: sure! renamed and move them up

File: providers/azure.go (hunk 18 above)
Comment (weinong) [reply providers/azure.go:315]: yeah, this logic looks weird, I feel it should be 
```go
if email == "" || err != nil {
```

File: providers/azure.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (weinong) [reply providers/azure.go:111]: sure!

File: providers/azure.go (hunk 18 above)
Comment (weinong) [reply providers/azure.go:315]: returning new error will be a change to existing behavior. I think I'm fine with it.

File: providers/azure.go (hunk 19 above)
Comment (weinong) [reply providers/azure.go:186]: sounds good

File: providers/azure.go (hunk 12 above)
Comment (weinong) [reply providers/azure.go]: happy to change. though, do you happen to know where this idiom is documented? @JoelSpeed

**Comment by weinong** [comment]
@NickMeves @JoelSpeed I believe I address all the actionable feedbacks! PTAL

File: providers/azure.go [hunk 21]
```diff
@@ -209,6 +268,17 @@ func (p *AzureProvider) redeemRefreshToken(ctx context.Context, s *sessions.Sess
 	s.RefreshToken = jsonResponse.RefreshToken
 	s.CreatedAt = &now
 	s.ExpiresOn = &expires
+
+	// the presence of id_token depends on the configuration and
+	// verification of id_token requires oidc configuration
+	if s.IDToken != "" && p.Verifier != nil {
```
Comment (NickMeves) [inline providers/azure.go:274]: You have this same blurb twice in redeem & refresh -- does it make sense to wrap all this in the logic of the helper method?

File: providers/azure.go [hunk 22]
```diff
@@ -149,13 +145,76 @@ func (p *AzureProvider) Redeem(ctx context.Context, redirectURL, code string) (*
...
+
+// EnrichSession finds the email to enrich the session state
+func (p *AzureProvider) EnrichSession(ctx context.Context, s *sessions.SessionState) error {
+	if s.Email != "" {
+		return nil
+	}
+
+	email, err := getEmailFromProfileAPI(ctx, s.AccessToken, p.ProfileURL.String())
+	if email == "" || err != nil {
+		err = fmt.Errorf("unable to get email address: %v", err)
```
Comment (NickMeves) [inline providers/azure.go:177]: I think this will lead to misleading error message with an empty trailing `:` when `email == ""` and `err == nil`

**Review by NickMeves — COMMENTED** [review]
Just a last couple of NITs -- Once we cleat those up and get a CHANGELOG entry in place, this looks good to go to me.

**Comment by codablock** [comment]
I'm wondering why it's not an option to grab the EMail from the access token? This would have the advantage that no extra validation and no oidc config would be needed. Am I missing something?

**Comment by weinong** [comment]
@codablock good question. I actually don't quite understand why email is even needed. That being said, when you say "no extra validation is needed", do you mean not to validate the access token? 

@NickMeves @JoelSpeed WDYT? I can just add an Azure specific flag specifying what claim in access token to be used for email.

**Comment by codablock** [comment]
My understanding is that we trust the access token at that point already, but I don't know enough about the oauth2-proxy codebase to to be 100% sure.

As an alternative, I've made a slight modification to this PR that allows it to fall back to using the access token in case the ID token fails to verify (which is the case for me due to the missing signature). With this commit, It seems to be working as expected and I'm now getting valid EMails. The commit can be found [here](https://github.com/codablock/oauth2-proxy/commit/29fa14e63cd31ad8708a63b9d2710df8098d6f84). You can cherry-pick it if you want. I'm going to use this in our system until this or an alternative solution is merged.

File: providers/azure.go (hunk 21 above)
Comment (weinong) [reply providers/azure.go]: refactored a bit

File: providers/azure.go (hunk 22 above)
Comment (weinong) [reply providers/azure.go]: refactored a bit

**Comment by NickMeves** [comment]
> My understanding is that we trust the access token at that point already, but I don't know enough about the oauth2-proxy codebase to to be 100% sure.
> 
> As an alternative, I've made a slight modification to this PR that allows it to fall back to using the access token in case the ID token fails to verify (which is the case for me due to the missing signature). With this commit, It seems to be working as expected and I'm now getting valid EMails. The commit can be found [here](https://github.com/codablock/oauth2-proxy/commit/29fa14e63cd31ad8708a63b9d2710df8098d6f84). You can cherry-pick it if you want. I'm going to use this in our system until this or an alternative solution is merged.

We trust the Access Token for details IF it was sent to a ProfileURL/userinfo endpoint AND that layer validated it and returned a JSON payload with user/email/group details.

Unless we can verify the token signature, we don't extract any JWT claims into session fields. Hence the IDToken + OIDC public discovery documents (particularly the `jwks_uri` endpoint) giving us a level of trust in ID Token claims.

If we have a scalable means to validate Access Token signatures, we can use its claims.

**Comment by NickMeves** [comment]
> I'm also wondering why the ID token needs extra verification when we just received it from Azure AD. I'm actually having issues with validation of it as I'm getting an ID token without a signature.

No signature?! That doesn't seem right or secure at all 🤔 

In you scopes, did you lead with `openid` so that Azure would be OIDC compliant and include an `id_token` field in its `token_endpoint` response (the `authorization_code` redeem stage of OAuth)?

**Comment by weinong** [comment]
no signature seems really odd. 

@NickMeves , access token can be validated just like id_token is. I can incorporate the fallback logic @codablock has in [his commit](https://github.com/codablock/oauth2-proxy/commit/29fa14e63cd31ad8708a63b9d2710df8098d6f84)

**Comment by NickMeves** [comment]
> id_token without signature seems really odd.
> 
> @NickMeves , access token can be validated just like id_token is. I can incorporate the fallback logic @codablock has in [his commit](https://github.com/codablock/oauth2-proxy/commit/29fa14e63cd31ad8708a63b9d2710df8098d6f84)

Yeah - I think that might be fine 🤔 

My only apprehension is that codepath then assumes you only received the standard OAuth fields in the JSON response from the token endpoint (`access_token`, `refresh_token`, `token_type`, `expires_in`) and not the additional `id_token` field OIDC layers on top of that OAuth endpoint -- meaning we aren't using OIDC.

But then we use OIDC constructs (its `openid-configuration` discovery document & `jwks_uri`) to validate the `access_token` signature?

This feels like a risky mix of paradigms that aren't guaranteed to always align. I don't think Azure is forced to stick with this overlap in either specification or their own documentation - do we run the risk of them altering their access token signing or structure?

Do we have official documentation from Azure on the proper way to verify access token signatures & claims? (and not just send them to an OAuth2 Profile URL endpoint for user details)

@JoelSpeed Do you have any background on this for Azure? I remember we chatted recently about some of the quirks of access/refresh tokens around Google and its semi-OIDC nature recently.

**Comment by weinong** [comment]
FWIW, Azure AD's token validation logic applies to ID Token as well as to access token. So I wouldn't worry about mixing the paradigms.

https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-tokens
https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#validating-an-id_token

> Validating an id_token is similar to the first step of validating an access token - your client can validate that the correct issuer has sent back the token and that it hasn't been tampered with. Because id_tokens are always a JWT token, many libraries exist to validate these tokens - we recommend you use one of these rather than doing it yourself.

**Comment by NickMeves** [comment]
> FWIW, Azure AD's token validation logic applies to ID Token as well as to access token. So I wouldn't worry about mixing the paradigms.
> 
> https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-tokens
> https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#validating-an-id_token
> 
> > Validating an id_token is similar to the first step of validating an access token - your client can validate that the correct issuer has sent back the token and that it hasn't been tampered with. Because id_tokens are always a JWT token, many libraries exist to validate these tokens - we recommend you use one of these rather than doing it yourself.

@weinong Thanks for the docs! I'm sold, sounds good to me!

**Comment by codablock** [comment]
Here is an issue I found while googling for non-signed ID tokens: https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/117

> We trust the Access Token for details IF it was sent to a ProfileURL/userinfo endpoint AND that layer validated it and returned a JSON payload with user/email/group details.
@NickMeves Is this really true? My understanding is that the call to the redeem URL is what we rely on to gain trust, as this is where we get the access token from. Same with the ID token, we got it from the redeem call so we can be sure it was issued by Azure. The signature verification based on the `jwks_uri` info is only required when the tokens are later passed to other applications, e.g. via the reverse proxy, as these can't otherwise assure that Azure issued them.

If my understanding is wrong and signature verification should also be done in oauth2-proxy, even when we get the tokens directly from Azure, then maybe this verification should happen all the time, directly after the redeem (at least for the access token). The `jwks_uri` for Azure follows a standard pattern as I understand, it's always `https://sts.windows.net/<tenant-id>/`, so we can do the verification even if `--oidc-issuer-url` was not passed.

**Comment by NickMeves** [comment]
> @NickMeves Is this really true? My understanding is that the call to the redeem URL is what we rely on to gain trust, as this is where we get the access token from. Same with the ID token, we got it from the redeem call so we can be sure it was issued by Azure. The signature verification based on the `jwks_uri` info is only required when the tokens are later passed to other applications, e.g. via the reverse proxy, as these can't otherwise assure that Azure issued them.

I want our security model to be robust and have defense in-depth against all potentially layers of attack. Hence I'm pretty firm about only trusting claims in tokens if signature verification has passed. MITM attacks with the IdP, leaked cookie-secret resulting in session cookie tampering, etc - whatever future attack comes up, we have a much better security position if we are diligent about verifying signatures before trusting.

> EDIT2: I just remembered that access tokens can't be easily verified in case the access token is for graph.microsoft.com, which is the default if you don't specify `--resource`, due to the way they included the [nonce](https://stackoverflow.com/questions/55247157/unable-to-validate-access-token-signature-obtained-from-azure-ad-in-order-to-sec). So, for the default `resource`, we must either rely on the fact that we have called Azure by ourself and obtained the token from Azure, or by invoking the profile API with the access token to get some extra verification.

Hopefully we'll have the nonce support taken care of soon: https://github.com/oauth2-proxy/oauth2-proxy/pull/967

In an ideal world, any OIDC providers are based on the central `OIDCProvider` - rather than Azure living in this split world supporting OIDC & OAuth, right? E.g. a new `azure-oidc` provider or something?

**Comment by NickMeves** [comment]
> Just a last couple of NITs -- Once we cleat those up and get a CHANGELOG entry in place, this looks good to go to me.

@weinong Ping me when this is ready for a final look and let me know what commits you add since my last review so I can quickly skim the changes. Then lets get this PR merged!

**Comment by weinong** [comment]
@NickMeves it's ready! the last commit is https://github.com/oauth2-proxy/oauth2-proxy/pull/914/commits/6e9d353501c7128bdc51f58dabe8fffc572693fd which implements what @codablock requested

File: providers/azure.go [hunk 23]
```diff
@@ -149,13 +145,103 @@ func (p *AzureProvider) Redeem(ctx context.Context, redirectURL, code string) (*
...
+	email, err := getEmailFromProfileAPI(ctx, s.AccessToken, p.ProfileURL.String())
+	if email == "" || err != nil {
+		if err != nil {
+			err = fmt.Errorf("unable to get email address, error: %v", err)
+		} else {
+			err = errors.New("unable to get email address")
+		}
+		logger.Errorf("%s", err)
+		return err
+	}
```
Comment (NickMeves) [inline providers/azure.go:180]: This nesting is a bit redundant - wen can clean it up the logical layers by returning early
```suggestion
        if err != nil {
	        return fmt.Errorf("unable to get email address: %v", err)
        }
        if email == "" {
	        return errors.New("unable to get email address")
        }
```

File: providers/azure.go [hunk 24]
```diff
@@ -149,13 +145,103 @@ func (p *AzureProvider) Redeem(ctx context.Context, redirectURL, code string) (*
...
+// https://github.com/oauth2-proxy/oauth2-proxy/pull/914#issuecomment-782285814
+// https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/117
+func (p *AzureProvider) verifyTokensAndExtractEmail(ctx context.Context, idToken, accessToken string) (string, error) {
+	email := ""
+	if p.Verifier == nil {
+		return "", nil
+	}
+
+	if idToken != "" {
+		token, err := p.Verifier.Verify(ctx, idToken)
```
Comment (NickMeves) [inline providers/azure.go:218]: These two snippets look almost identical - can we just make a generic verify + extract claims from token methods and call it twice (once for id_token, fallback to access token)

File: providers/azure.go [hunk 25]
```diff
@@ -230,53 +323,32 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
...
 	return email, err
 }
 
-// GetEmailAddress returns the Account email address
-func (p *AzureProvider) GetEmailAddress(ctx context.Context, s *sessions.SessionState) (string, error) {
-	var email string
-	var err error
-
-	if s.AccessToken == "" {
+func getEmailFromProfileAPI(ctx context.Context, accessToken, profileURL string) (string, error) {
```
Comment (NickMeves) [inline providers/azure.go:337]: I think you should use `(p *AzureProvider)` as the method receiver on this so you don't have to explicitly extract and pass the `profileURL`.

You can see nearly identical functionality as this in the OIDCProvider:

```
// enrichFromProfileURL enriches a session's Email & Groups via the JSON response of
// an OIDC profile URL
func (p *OIDCProvider) enrichFromProfileURL(ctx context.Context, s *sessions.SessionState) error {
```

File: providers/azure.go [hunk 26]
```diff
@@ -230,53 +323,32 @@ func getEmailFromJSON(json *simplejson.Json) (string, error) {
 		err = otherMailsErr
 	}
 
+	if err != nil || email == "" {
+		email, err = json.Get("userPrincipalName").String()
```
Comment (NickMeves) [inline providers/azure.go:327]: I think this is fine to keep for this PR since the pattern already existed, but in case you want to remedy the design while you are extending it.

In cases where the JSON schema response is static, we should use a struct with JSON tags.

We really only use `simplejson` when fields in the JSON response are configurable by the user with config flags.

File: providers/azure.go [hunk 27]
```diff
@@ -149,13 +145,103 @@ func (p *AzureProvider) Redeem(ctx context.Context, redirectURL, code string) (*
...
 		IDToken:      jsonResponse.IDToken,
 		CreatedAt:    &created,
 		ExpiresOn:    &expires,
 		RefreshToken: jsonResponse.RefreshToken,
-	}, nil
+	}
+
+	email, err := p.verifyTokensAndExtractEmail(ctx, session.IDToken, session.AccessToken)
+	if err != nil {
+		return nil, err
```
Comment (NickMeves) [inline providers/azure.go:158]: Do you really want to completely fail and return a nil session if email claims to session extraction failed? Isn't the `EnrichSession` call after this hitting the Profile URL the fallback to get an email via that mechanism?

File: providers/azure_test.go [hunk 28]
```diff
@@ -122,98 +157,154 @@ func testAzureBackend(payload string) *httptest.Server {
...
-func TestAzureProviderRedeemReturnsIdToken(t *testing.T) {
-	b := testAzureBackend(`{ "id_token": "testtoken1234", "expires_on": "1136239445", "refresh_token": "refresh1234" }`)
-	defer b.Close()
-	timestamp, err := time.Parse(time.RFC3339, "2006-01-02T22:04:05Z")
-	assert.Equal(t, nil, err)
+	for _, testCase := range testCases {
+		t.Run(testCase.Name, func(t *testing.T) {
+			idTokenString := ""
+			accessTokenString := ""
+			if testCase.EmailFromIDToken != "" {
```
Comment (NickMeves) [inline providers/azure_test.go:262]: 2 test cases I think need adding to get better coverage:

- Email in both a valid IDToken & Access Token
- Call to Redeem URL fails and results in an error

File: providers/azure_test.go [hunk 29]
```diff
@@ -122,98 +157,154 @@ func testAzureBackend(payload string) *httptest.Server {
...
+		ExpiresOn            string
+		EmailFromIDToken     string
+		EmailFromAccessToken string
+		IsIDTokenMalformed   bool
+	}{
+		{
+			Name:             "with id_token returned",
+			EmailFromIDToken: "foo1@example.com",
+			RefreshToken:     "some_refresh_token",
+			ExpiresOn:        "2006-01-02T22:04:05Z",
```
Comment (NickMeves) [inline providers/azure_test.go:241]: This feels a little weird to mock without being able to mock the session `CreatedAt` (since azure provider explicitly calls `time.Now()`) -- getting test sessions out of this where the expires date is years before the created data might get us into weird trouble in the future if functionality changes.

Can we set this to a variable set `time.Now()` + 1 hour duration and check that in assertions below?

Comment (NickMeves) [reply providers/azure_test.go:241]: (I understand you are just copying this logic over -- but looking at the dated style of these Azure unit tests, this provider's test suite needs some love. So lets try to fix up oddities we catch in the diff).

File: providers/azure.go (hunk 24 above)
Comment (weinong) [reply providers/azure.go:218]: do you think this is necessary? If I refactor this way, I will have to break down the calling function to appease the static analysis :-/

File: providers/azure.go (hunk 27 above)
Comment (weinong) [reply providers/azure.go:158]: right, I will update

File: providers/azure.go (hunk 24 above)
Comment (NickMeves) [reply providers/azure.go:218]: We can leave it if you are having trouble with the codeclimate checks.

The current construction is just a little hard to read - it has way too many nested if/else loops than we prefer in the project's general code style. We aim for using "early returns" & helper methods to reduce deep nesting of conditional logic.

Unrelated: these `logger.Printf` in the error cases should be `logger.Errorf`, right?

Comment (weinong) [reply providers/azure.go:218]: nvm, found a way to refactor this!

File: providers/azure.go (hunk 26 above)
Comment (weinong) [reply providers/azure.go:327]: i will leave it as is for now. really need to wrap this up :)

File: providers/azure_test.go (hunk 29 above)
Comment (weinong) [reply providers/azure_test.go:241]: sure

File: providers/azure_test.go (hunk 28 above)
Comment (weinong) [reply providers/azure_test.go:262]: sure

**Review by NickMeves — APPROVED** [review]
Thanks for hanging in there while we worked out the refactors around this behavior. LGTM!

**Comment by NickMeves** [comment]
Oh - this needs a CHANGELOG entry.

@weinong Once you add that I will merge.

**Comment by weinong** [comment]
@NickMeves which header should I update under?

# Vx.x.x (Pre-release)

this?

**Comment by NickMeves** [comment]
> @NickMeves which header should I update under?
> 
> # Vx.x.x (Pre-release)
> this?

The top of this block with these other 10+ unreleased PRs: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/CHANGELOG.md#changes-since-v701

**Review by NickMeves — APPROVED** [review]

**Comment by weinong** [comment]
omg it's merged! @NickMeves do you know when the release will be cut and when container image will be available?

**Comment by NickMeves** [comment]
> omg it's merged! @NickMeves do you know when the release will be cut and when container image will be available?

We think we have a critical mass of features focused around prometheus metrics & UI improvements to release v7.1 rather soon. @JoelSpeed and I will meet tomorrow and lock in the final PRs we want to merge before v7.1

**Comment by JoelSpeed** [comment]
You can take a look at our [project](https://github.com/oauth2-proxy/oauth2-proxy/projects/5) for the release which shows what we currently are planning for this release. We will likely update this after our chat tomorrow though

**Comment by weinong** [comment]
please consider to include this in the release as there are some customers blocked by this. thanks!

**Comment by NickMeves** [comment]
> please consider to include this in the release as there are some customers blocked by this. thanks!

Yup! It will be there. Everything merged in master will be included.
