### PR TITLE
Use gorilla mux for OAuth Proxy routing

### LINKED ISSUE #992: Inject request and response headers even for skipped routes
(loosely connected to #985 and #979) 

## Current Behavior

Currently, `oauth2-proxy` supports two modes of operation:

1. Protect an endpoint and either return 401 if unauthenticated or proxy endpoint's response if authenticated
2. Provide full access without any intervention if `--skip-auth-route` is set for the endpoint.

It's an all-or-nothing approach, however, there is quite a bit of middle ground to be covered. For example:

1. An endpoint which can optionally accept authentication
2. An endpoint which requires complex groups and roles evaluation from the token
3. An endpoint which needs to check for user permissions based on business logic 

At the same time, `oauth2-proxy` does a lot of heavy lifting, which makes implementing a custom authentication solution undesirable. 

## Expected Behavior

If a route is excluded from authentication handling by setting `--skip-auth-route`, authentication headers should still get injected if authenticated.

## Possible Solution

In my local code, I've managed to make this work by applying the following patch.

```diff
@@ -977,6 +977,10 @@ func (p *OAuthProxy) AuthOnly(rw http.ResponseWriter, req *http.Request) {
 
 // SkipAuthProxy proxies allowlisted requests and skips authentication
 func (p *OAuthProxy) SkipAuthProxy(rw http.ResponseWriter, req *http.Request) {
+       session, err := p.getAuthenticatedSession(rw, req)
+       if err == nil {
+               p.addHeadersForProxying(rw, req, session)
+       }
        p.headersChain.Then(p.serveMux).ServeHTTP(rw, req)
 }
```

However:
1. I can't explain to myself why this works. From what I gather from the code, `p.addHeadersForProxying` has nothing to do with header injection, which is handled in `p.headersChain`, which looks like it should be doing the injection already, but does not.
2. I failed to understand the structure of request/response tests, so I couldn't write one (which is not really surprising, considering I have written about 3 lines of Go in my life). 

## Steps to Reproduce (for bugs)

1. Set `--skip-auth-routes` to something like `.*` or anything else you can easily grab
2. Set injection configuration to inject something in response headers (because it's easily seen in browser)
3. Make sure you are authenticated (by calling `/oauth2/sign_in`)
4. Open browser's developer tools 
5. Open a skipped endpoint in browser
6. Observe that request in developer tools noticing missing injected response header 

## Your Environment
- Version used: latest `master` git snapshot

### PR DESCRIPTION
**Pull request by JoelSpeed**
## Description

Replaces the old switch statement we have with a proper router.
Now we use gorilla/mux to do the routing of the application which should hopefully allow us to start breaking things down a bit in the main OAuthProxy application layer.

Every path now that needs a session, has the session chain called out in the `buildServeMux` when the path is registered.
Eventually we will expand the session chain to become an auth chain, and the authorization that happens immediately after the session chain in each of these will become part of that chain. Which should mean that the handlers after these are just that, the handlers, with all the shared logic separated out.

## Motivation and Context

Trying to make the flow simpler to understand, using standard tooling/patterns should hopefully make this simpler.

Fixes #992 

## How Has This Been Tested?

Manually using the local testing environment + unit tests

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

File: oauthproxy.go [hunk 1]
```diff
@@ -1145,12 +1153,12 @@ func validOptionalPort(port string) bool {
...
+	session := middlewareapi.GetRequestScope(req).Session
 
-	getSession := p.sessionChain.Then(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
-		session = middlewareapi.GetRequestScope(req).Session
-	}))
-	getSession.ServeHTTP(rw, req)
+	// Check this after loading the session so that if a valid session exists, we can add headers from it
+	if p.IsAllowedRequest(req) {
+		return session, nil
+	}
```
Comment (JoelSpeed) [inline oauthproxy.go:1161]: Do we need to validate that the session is also valid before we return it? Could this be a security hole if we return what would otherwise be an invalid session? Eg, if someones IP allows them through but their session does not have the correct group requirements? Should the session be passed here or not? (CC @ianroberts @NickMeves)

Comment (NickMeves) [reply oauthproxy.go:1161]: I can't remember where this got fixed? I vaguely recall an issue asking for adding session headers to skipped routes if a session exists and doing nothing otherwise? Did we implement that?

Either way -- I think even if the AuthZ logic on session fields would fail, we still pass it to the backend if they are under a `IsAllowedRequest`. People have wanted the `X-Forwarded-*` auth headers to perform their own optional AuthZ logic on the backend when they need to share the allowed route with some external/API requests that can't auth.

Comment (NickMeves) [reply oauthproxy.go:1161]: Or is this us implementing that functionality for the first time? 😄

Comment (JoelSpeed) [reply oauthproxy.go:1161]: This is us doing it for the first time, but yeah, there have been some issues discussing it!

I do wonder  whether it is a security issue to be passing an invalid session to the backend if they have an allowed request.

@ianroberts was one of the people involved in the original issue about injecting this, perhaps he has a moment to chime in? 

If the session is invalid (ie doesn't match the email validation or has an expired token or something like that), do we expect the headers to be injected or do we expect the session to be ignored as it doesn't pass authz?

Comment (JoelSpeed) [reply oauthproxy.go:1161]: Actually, the more I think about it, it should be a valid session as we don't put it into the scope unless it's valid, so I think this is safe as is. I think this PR is actually ok to merge, but we should wait until the release first

Comment (ianroberts) [reply oauthproxy.go:1161]: > we don't put it into the scope unless it's valid

Indeed, that's my reading of the various session loader middlewares too - `scope.Session = ...` is always the last thing the handler functions do before delegating to the next handler in the chain.

Comment (ianroberts) [reply oauthproxy.go:1161]: P.S. @JoelSpeed I've implemented a bit of logic at https://github.com/ianroberts/oauth2-proxy/tree/proxy-router on top of this PR to suppress the various "couldn't load session" log messages in the case where the session is optional (i.e. the route is skipped), if that's of interest.

Comment (NickMeves) [reply oauthproxy.go:1161]: > Actually, the more I think about it, it should be a valid session as we don't put it into the scope unless it's valid, so I think this is safe as is. I think this PR is actually ok to merge, but we should wait until the release first

Yeah - the `Authorize` method for each provider is called as the final step to the sign-in flow before a session is created (in addition to subsequently on every request). That was missing on the initial implementation, but caused security/logic issues for the subrequest flow if I recall?

But yes - our sessions should all be valid.

**Comment by JoelSpeed** [comment]
I think this PR is ready for review, I have nothing more planned for it before we merge and it seems we have resolved the question about whether sessions are injected or not when they're invalid, so should be good to go

File: oauthproxy.go [hunk 2]
```diff
@@ -270,6 +269,39 @@ func (p *OAuthProxy) setupServer(opts *options.Options) error {
...
 
+func (p *OAuthProxy) buildServeMux(proxyPrefix string) {
+	r := mux.NewRouter()
+	// Everything served by the router must go through the preAuthChain first.
+	r.Use(p.preAuthChain.Then)
+
+	// Register the robots path writer
+	r.Path(robotsPath).HandlerFunc(p.pageWriter.WriteRobotsTxt)
+
+	// The authonly path should be registered separately to prevent it from getting no-cache headers
```
Comment (NickMeves) [inline oauthproxy.go:280]: Do you have historical context why this is? (might be handy to add to the comment why it is excluded). I can't readily think of why this case for subrequests to `/oauth2/auth` need to have no-cache headers stripped, so it might be a weird corner case worth commenting?

File: oauthproxy.go [hunk 3]
```diff
@@ -188,18 +192,11 @@ func NewOAuthProxy(opts *options.Options, validator func(string) bool) (*OAuthPr
...
 		Validator:      validator,
 
-		RobotsPath:        "/robots.txt",
-		SignInPath:        fmt.Sprintf("%s/sign_in", opts.ProxyPrefix),
-		SignOutPath:       fmt.Sprintf("%s/sign_out", opts.ProxyPrefix),
-		OAuthStartPath:    fmt.Sprintf("%s/start", opts.ProxyPrefix),
-		OAuthCallbackPath: fmt.Sprintf("%s/callback", opts.ProxyPrefix),
-		AuthOnlyPath:      fmt.Sprintf("%s/auth", opts.ProxyPrefix),
-		UserInfoPath:      fmt.Sprintf("%s/userinfo", opts.ProxyPrefix),
+		SignInPath: fmt.Sprintf("%s/sign_in", opts.ProxyPrefix),
```
Comment (NickMeves) [inline oauthproxy.go:195]: Is this used?

File: oauthproxy.go [hunk 4]
```diff
@@ -188,18 +192,11 @@ func NewOAuthProxy(opts *options.Options, validator func(string) bool) (*OAuthPr
 		CookieSameSite: opts.Cookie.SameSite,
 		Validator:      validator,
 
-		RobotsPath:        "/robots.txt",
```
Comment (NickMeves) [inline oauthproxy.go:191]: Nice! It is getting even smaller!

File: oauthproxy.go [hunk 5]
```diff
@@ -531,39 +563,7 @@ func (p *OAuthProxy) IsValidRedirect(redirect string) bool {
...
-func (p *OAuthProxy) serveHTTP(rw http.ResponseWriter, req *http.Request) {
-	if req.URL.Path != p.AuthOnlyPath && strings.HasPrefix(req.URL.Path, p.ProxyPrefix) {
-		prepareNoCache(rw)
-	}
-
-	switch path := req.URL.Path; {
-	case path == p.RobotsPath:
-		p.RobotsTxt(rw, req)
-	case p.IsAllowedRequest(req):
-		p.SkipAuthProxy(rw, req)
```
Comment (NickMeves) [inline oauthproxy.go:546]: Where did this case go? I'm not seeing it readily above in the new router setup

Comment (ianroberts) [reply oauthproxy.go:546]: This is the reason why this PR fixes #992 - rather than making a special case for skipped routes/pre-approved source IPs and passing straight through to the upstream without attempting to load the session, this PR rearranges things so that _all_ requests go through the `sessionChain` first and then the `IsAllowedRequest` check happens in `getAuthenticatedSession`.

The logic has changed from

  - if IsAllowedRequest
    - then proxy
    - else
      - try loading session
      - if session was loaded successfully
        - then proxy
        - else redirect to signin

to

  - try loading session
  - if IsAllowedRequest _or_ session was loaded successfully
    - then proxy
    - else redirect to signin

which has the side effect of adding headers whenever there's a valid session available, even if the route is skipped or the source IP is allowlisted.

Comment (NickMeves) [reply oauthproxy.go:546]: Ah thanks! I see the flow now

File: oauthproxy.go [hunk 6]
```diff
@@ -1130,12 +1138,12 @@ func validOptionalPort(port string) bool {
...
 func (p *OAuthProxy) getAuthenticatedSession(rw http.ResponseWriter, req *http.Request) (*sessionsapi.SessionState, error) {
-	var session *sessionsapi.SessionState
+	session := middlewareapi.GetRequestScope(req).Session
 
-	getSession := p.sessionChain.Then(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
-		session = middlewareapi.GetRequestScope(req).Session
-	}))
-	getSession.ServeHTTP(rw, req)
+	// Check this after loading the session so that if a valid session exists, we can add headers from it
+	if p.IsAllowedRequest(req) {
```
Comment (NickMeves) [inline oauthproxy.go:1144]: So I understand the motivation here to get headers from sessions into passthrough allowed paths.

But is this this the right place to do the `IsAllowedRequest` check in the nesting? Now it is applied to more endpoints than just `Proxy` (userinfo, auth) and the logic for this allowlist codepath is a little obfuscated.

Is there a way to make it its own explicit method decoupled from `getAuthenticatedSession` to keep the concerns separate?

Comment (NickMeves) [reply oauthproxy.go:1144]: Also, I can't remember if I touched on this in the original Issue reporting:

Is injecting in headers if a session happens to exist for an allowed request a breaking change. I've run into scenarios in the past where users would allowlist a path and then inject their explicit override for a specific header for that route.

If we have header middleware, we'd override or strip those for security purposes right?

I'll also need to think about session vs no session allowed paths and how header security works a bit more.

File: oauthproxy.go (hunk 2 above)
Comment (JoelSpeed) [reply oauthproxy.go:280]: We excluded this from the no-cache because of users using nginx caching to reduce the number of request to OAuth2 Proxy. By setting the no cache headers this caching is prevented. By allowing caching here, nginx can effectively do a single flight and return that result to multiple concurrent requests.

I used to have this set up at Pusher and had a 3 second cache. Greatly reduced the chance of double refreshes and the logout issues those incur.

File: oauthproxy.go (hunk 3 above)
Comment (JoelSpeed) [reply oauthproxy.go:195]: It's still used in one place in the proxy logic, I think when it's deciding whether to log the user in when they haven't gone directly to the sign in/start page

File: oauthproxy.go (hunk 6 above)
Comment (JoelSpeed) [reply oauthproxy.go:1144]: > But is this this the right place to do the IsAllowedRequest check in the nesting? Now it is applied to more endpoints than just Proxy (userinfo, auth) and the logic for this allowlist codepath is a little obfuscated.

At this point, `getAuthenticatedSession` acts as our authorization logic (should probably rename it). So this logic fits with the rest of the content of this method at least. I think once we get our authz layer sorted, this function will go away completely.

The rest of your questions are all valid but I haven't had a chance to really look into or think about this now. It's been so long since I implemented this initially that I can't remember what's going on

Comment (JoelSpeed) [reply oauthproxy.go:1109]: > But is this this the right place to do the IsAllowedRequest check in the nesting? Now it is applied to more endpoints than just Proxy (userinfo, auth) and the logic for this allowlist codepath is a little obfuscated.

Previously, the `IsAllowedRequest` was really early in the switch statement. So if you accessed `Userinfo` or `Auth`, and were an allowed request, you actually got directed back to the `Proxy`. Ergo, if you had a valid SkipAuth and a valid session, there was no way to access userinfo or the auth endpoint. So I think with this change, we are fixing a bug. We aren't applying the `IsAllowedRequest` to more endpoints as it previously trumped these other endpoints anyway

Comment (JoelSpeed) [reply oauthproxy.go:1111]: > Is injecting in headers if a session happens to exist for an allowed request a breaking change. I've run into scenarios in the past where users would allowlist a path and then inject their explicit override for a specific header for that route.
>
> If we have header middleware, we'd override or strip those for security purposes right?

We already have the headers chain in the path for anything that skips the auth route anyway, so it would have stripped anything that a user tried to inject that matched any header we would set. Ergo I don't see this as a breaking change. We are simply adding extra info where before there was none. If the user had turned off the stripping, this may be a change but we have discussed security implications of this before and I think it's up to the user how they want to deal with this (they'll probably already be doing so for when it's not an allowed route)

File: oauthproxy.go [hunk 7]
```diff
@@ -258,6 +257,41 @@ func (p *OAuthProxy) setupServer(opts *options.Options) error {
...
+	r := mux.NewRouter()
+	// Everything served by the router must go through the preAuthChain first.
+	r.Use(p.preAuthChain.Then)
+
+	// Register the robots path writer
+	r.Path(robotsPath).HandlerFunc(p.pageWriter.WriteRobotsTxt)
+
+	// The authonly path should be registered separately to prevent it from getting no-cache headers.
+	// We do this to allow users to have a short cache (via nginx) of the response to reduce the
+	// likelihood of multiple reuests trying to referesh sessions simultaneously.
```
Comment (NickMeves) [inline oauthproxy.go:270]:
```suggestion
	// likelihood of multiple requests trying to refresh sessions simultaneously.
```

**Review by NickMeves — APPROVED** [review]
LGTM! Feel free to merge after you resolve the CHANGELOG conflicts without waiting for me to return to approve again.
