### PR TITLE
Adapt isAjax to support mimetype lists

### LINKED ISSUE #988: isAjax doesn't work with multiple accepted mime types
## Expected Behavior

`isAjax` in `oauthproxy.go` should be iterating through different mime types for the `Accept: ` field and return `true` if `application/json` is found. 

## Current Behavior

`isAjax` iterates over a single string. If this string matches `application/json` exactly, `isAjax` works as intended. With multiple mime types, as allowed by standards and [default for Axios](https://github.com/axios/axios/blob/b7e954eba3911874575ed241ec2ec38ff8af21bb/lib/defaults.js#L86), `isAjax` fails to find the correct mime type. The following test fails, proving the point.

```
func TestAjaxUnauthorizedRequestAccept1(t *testing.T) {
	header := make(http.Header)
	header.Add("Accept", "application/json, text/plain, */*")

	testAjaxUnauthorizedRequest(t, header)
}
```

## Possible Solution

Fix the loop to actually iterate over multiple mime types.

### PR DESCRIPTION
**Pull request by rassie**
## Description

Fixes #988

## How Has This Been Tested?

Included a unit test

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

File: oauthproxy.go [hunk 1]
```diff
@@ -1111,9 +1111,18 @@ func (p *OAuthProxy) addHeadersForProxying(rw http.ResponseWriter, req *http.Req
...
 	acceptValues := req.Header.Values("Accept")
 	const ajaxReq = applicationJSON
+	// Iterate over multiple Accept headers, i.e.
+	// Accept: application/json
+	// Accept: text/plain
 	for _, v := range acceptValues {
-		if v == ajaxReq {
-			return true
+		// Iterate over multiple mimetypes in a single header, i.e.
+		// Accept: application/json, text/plain, */*
```
Comment (NickMeves) [inline oauthproxy.go:1119]: The original intent of this was to figure out non-human driven requests that couldn't handle a redirect to a signin page (e.g. SPA backend API requests, machine to machine API auth). At least that's the only spot this function is used.

Are there scenarios where normal human driven interactions would have multiple headers (including `application/json`) and need the login redirect and don't want the `401 Unauthorized` a `true` from this would result in?

I don't know all the nuances of various browsers or client environments to answer this confidently.

Comment (rassie) [reply oauthproxy.go:1119]: > Are there scenarios where normal human driven interactions would have multiple headers (including application/json) and need the login redirect and don't want the 401 Unauthorized a true from this would result in?

("multiple headers" use-case is covered in current code, what you probably think about is "multiple mimetypes in one header" case, which is what I've extended) 

I don't think so, but I might be missing some edge-case too. However, XHR detection is failing right now with clients using multiple mimetypes by default (e.g. Axios, which is still extremely popular). The reasoning for multiple mimetypes is probably a kind of catch-all -- think about APIs working with JSON, but occasionally returning images. I honestly can't imagine breaking someone's use case, since they'd be knowingly relying on buggy behavior, and this patch corrects what has been intended, since finding `application/json` in `Accept` headers has been the intention of `isAjax` all along.

PS. BTW, `*/*` would match `application/json` too, but that's a bit far-fetched as an XHR indicator.

Comment (NickMeves) [reply oauthproxy.go:1119]: Good point, I completely missed in the diff the multi-acceptValues was already supported. So this is likely fine as well 👍

File: oauthproxy.go [hunk 2]
```diff
@@ -1111,9 +1111,18 @@ func (p *OAuthProxy) addHeadersForProxying(rw http.ResponseWriter, req *http.Req
...
+		for _, y := range strings.Split(v, ",") {
```
Comment (NickMeves) [inline oauthproxy.go:1120]: NIT: what is `y` short for? If it doesn't stand for anything can we get a more descriptive variable name?

**Comment by NickMeves** [comment]
This looks good to me. Can you add a CHANGELOG entry?

File: oauthproxy.go (hunk 2 above)
Comment (rassie) [reply oauthproxy.go:1120]: More or less "extended `v`". I'll find some name.

**Comment by rassie** [comment]
* CHANGELOG updated
* variables renamed

@NickMeves I've renamed `v` too, I hope it's OK.

**Review by NickMeves — APPROVED** [review]
LGTM! Thanks!
